project_id = "iyejaxnugjgjeceqdcky"

[functions.lemon-squeezy-webhook]
verify_jwt = false

[functions.daily-summary]
verify_jwt = false

[functions.send-recovery-emails]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false