import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'he' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  he: {
    // General
    'app.tagline': 'באף את השגרה, שחרר את הפוטנציאל',
    'app.syncProgress': 'התחבר כדי לסנכרן את ההתקדמות שלך',
    
    // Auth
    'auth.login': 'התחברות',
    'auth.signup': 'הרשמה',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.displayName': 'שם תצוגה',
    'auth.yourName': 'השם שלך',
    'auth.iAm': 'אני...',
    'auth.parent': 'הורה',
    'auth.teen': 'נער/ה',
    'auth.familyCode': 'קוד משפחה',
    'auth.familyCodePlaceholder': 'הדבק כאן את הקוד מההורה',
    'auth.familyCodeHint': 'בקש מההורה שלך את קוד המשפחה כדי להצטרף.',
    'auth.loggingIn': 'מתחבר...',
    'auth.creatingAccount': 'יוצר חשבון...',
    'auth.connect': 'התחבר',
    'auth.createAccount': 'צור חשבון',
    'auth.fillAllFields': 'אנא מלא את כל השדות',
    'auth.passwordMinLength': 'הסיסמה חייבת להכיל לפחות 6 תווים',
    'auth.enterFamilyCode': 'אנא הזן את קוד המשפחה מההורה',
    'auth.invalidCredentials': 'אימייל או סיסמה שגויים',
    'auth.emailExists': 'אימייל זה כבר רשום במערכת',
    'auth.invalidFamilyCode': 'קוד משפחה לא תקין',
    'auth.welcomeBack': 'ברוך שובך!',
    'auth.accountCreated': 'החשבון נוצר בהצלחה! ברוך הבא למשפחה!',
    'auth.orContinueWith': 'או המשך עם',
    'auth.continueWithGoogle': 'התחבר עם גוגל',
    'auth.signupWithGoogle': 'הירשם עם גוגל',
    'auth.googleRoleSelection': 'לאחר ההתחברות תוכל לבחור אם להירשם כהורה או כילד',
    'auth.googleSetupRequired': 'כדי להשתמש בגוגל, יש להגדיר קודם פרטי משתמש',
    
    // Navigation
    'nav.features': 'תכונות',
    'nav.howItWorks': 'איך זה עובד',
    'nav.forParents': 'להורים',
    'nav.login': 'התחבר',
    'nav.getStarted': 'התחל עכשיו',
    
    // Landing Page
    'landing.basedOnCogFun': 'מבוסס על עקרונות תפקודים ניהוליים',
    'landing.executiveFunction': 'כוח-העל לתפקודים',
    'landing.powerUp': 'הניהוליים',
    'landing.heroDescription': 'שלוט בשגרה היומית עם אסטרטגיות מקצועיות מבוססות מחקר, מותאמות למוח ה-ADHD.',
    'landing.tryFree': 'נסה BUFF בחינם',
    'landing.seeHow': 'ראה איך זה עובד',
    'landing.unlockBuffs': 'שחרר את הבאפים היומיים שלך',
    'landing.unlockDescription': 'כוחות קוגניטיביים שהופכים משימות מציפות לניצחונות ברי השגה.',
    'landing.activateBuffs': 'הפעל באפים יומיים',
    'landing.activateDescription': 'השתמש באסטרטגיות קוגניטיביות כדי לפרוץ שיתוק משימות ולכבוש משימות "הר" צעד אחר צעד.',
    'landing.familySync': 'סנכרון משפחתי',
    'landing.familySyncDescription': 'הגדרת יעדים משותפת כאשר ההורה הוא המאמן והנער הוא הגיבור של המסע שלו.',
    'landing.smartInsights': 'תובנות חכמות',
    'landing.smartInsightsDescription': 'לוח בקרה מבוסס נתונים שעוזר להורים לזהות דפוסים ולהציע תמיכה נכונה בזמן הנכון.',
    'landing.powerUpsFor': 'כוחות-על למוח ה-ADHD',
    'landing.powerUpsDescription': 'BUFF משתמש בגישה מקצועית לחיזוק תפקודים ניהוליים כדי לספק אסטרטגיות קוגניטיביות מותאמות אישית בדיוק כשהנער שלך צריך אותן.',
    'landing.environmentBuffs': 'באפים סביבתיים',
    'landing.environmentDescription': 'בצע אופטימיזציה של המרחב שלך לריכוז והפחת הסחות חושיות.',
    'landing.focusBuffs': 'באפים לריכוז',
    'landing.focusDescription': 'פרק משימות מציפות להישגים קטנים.',
    'landing.energyBuffs': 'באפים לאנרגיה',
    'landing.energyDescription': 'טכניקות ויסות עצמי לניהול אנרגיה ורגשות.',
    'landing.forParentsTitle': 'להורים: היו המאמן, לא הבוס',
    'landing.forParentsDescription': 'BUFF מעצים הורים עם תובנות ואסטרטגיות לתמיכה בפיתוח התפקודים הניהוליים של הנער שלהם ללא ניהול מיקרו. שיתוף פעולה על פני שליטה.',
    'landing.patternRecognition': 'זיהוי דפוסים',
    'landing.patternDescription': 'זהה מתי ואיפה קורים קשיים כדי להציע תמיכה ממוקדת.',
    'landing.coachingTips': 'טיפים לאימון',
    'landing.coachingDescription': 'קבל הצעות מבוססות מחקר לתמיכה בנער שלך.',
    'landing.collaborativeGoals': 'יעדים משותפים',
    'landing.collaborativeDescription': 'הגדר פרסים ואבני דרך יחד כצוות.',
    'landing.readyToPowerUp': 'מוכנים להתחזק?',
    'landing.joinFamilies': 'הצטרפו למשפחות שהופכות שגרות יומיות לניצחונות ברי השגה.',
    'landing.startFreeTrial': 'התחל תקופת ניסיון חינם',
    'landing.researchBacked': 'מבוסס על עקרונות לחיזוק תפקודים ניהוליים — אסטרטגיות קוגניטיביות מבוססות מחקר',
    
    // Dashboard
    'dashboard.dailyXP': 'XP יומי',
    'dashboard.todaysTasks': 'משימות היום',
    'dashboard.completed': 'הושלמו',
    'dashboard.pending': 'ממתינות',
    'dashboard.buffActivated': 'באף הופעל!',
    'dashboard.noTasks': 'אין משימות להיום',
    
    // Tasks
    'task.morning': 'בוקר',
    'task.afternoon': 'צהריים',
    'task.evening': 'ערב',
    'task.medication': 'תרופות',
    'task.hygiene': 'היגיינה',
    'task.nutrition': 'תזונה',
    'task.school': 'לימודים',
    
    // Settings
    'settings.title': 'הגדרות',
    'settings.general': 'כללי',
    'settings.language': 'שפה',
    'settings.hebrew': 'עברית',
    'settings.english': 'English',
    'settings.dailyGoal': 'יעד יומי',
    'settings.appTitle': 'כותרת האפליקציה',
    'settings.lessonReminders': 'תזכורות שיעורים',
    'settings.save': 'שמור',
    'settings.cancel': 'ביטול',
    'settings.parentSettings': 'הגדרות הורה',
    'settings.signOut': 'התנתק',
    
    // Parent Mode
    'parent.overview': 'סקירה',
    'parent.children': 'ילדים',
    'parent.tasks': 'משימות',
    'parent.timetable': 'מערכת שעות',
    'parent.rewards': 'פרסים',
    'parent.insights': 'תובנות',
    'parent.familyCode': 'קוד משפחה',
    'parent.shareCode': 'שתף קוד',
    'parent.sendToChild': 'שלח לילד',
    'parent.noChildren': 'אין ילדים רשומים עדיין',
    'parent.inviteChild': 'הזמן ילד להצטרף למשפחה',
    
    // Rewards Store
    'store.title': 'חנות פרסים',
    'store.subtitle': 'מימוש הקרדיטים שצברת',
    'store.balance': 'יתרה',
    'store.totalBalance': 'סה״כ יתרה',
    'store.claim': 'מימוש',
    'store.claimed': 'מומש',
    'store.locked': 'נעול',
    'store.notEnough': 'אין מספיק קרדיטים',
    'store.availableRewards': 'פרסים זמינים',
    'store.claimedRewards': 'פרסים שמומשו',
    'store.noRewards': 'אין פרסים עדיין',
    'store.askParent': 'בקש מההורה להוסיף פרסים מגניבים!',
    'store.vaultEmpty': 'הכספת ריקה',
    'store.askParentToAdd': 'בקש מההורה להוסיף פרסים למסע שלך!',
    'store.credits': 'קרדיטים',
    'store.rewardPurchased': '🎉 פרס נרכש!',
    'store.enjoy': 'תהנה!',
    'store.unclaim': 'ביטול מימוש',
    'store.unclaimConfirmTitle': '↩️ ביטול מימוש?',
    'store.unclaimConfirmDesc': 'יחזור לחנות',
    'store.unclaimCreditsReturn': 'נקודות יוחזרו ליתרה',
    'store.unclaimSuccess': '↩️ פרס הוחזר',
    'store.unclaimCreditsReturned': 'נקודות הוחזרו',
    'store.confirmCancel': 'ביטול',
    'store.confirmOk': 'אישור',
    'store.effortMessage': 'כל פרס כאן הרווחת בעצמך, דרך העבודה הקשה שלך! 💪',
    
    // Pet
    'pet.resting': '😴 החיית המחמד נחה...',
    'pet.restEncouragement': 'זה הזמן לצאת ולעשות משהו כיף בעולם האמיתי!',
    'pet.happyReaction': 'וואו!',
    'pet.restingTitle': 'זמן מנוחה',
    'pet.restMessage': 'אני טעון לגמרי! הולך לנוח קצת בזמן שאתה הולך לכבוש את העולם. נתראה אחרי המשימה הבאה שלך!',
    'pet.levelUp': 'עלייה ברמה! 🎉',
    'pet.greeting.ready': 'היי {name}! מוכן למשימה הבאה?',
    'pet.greeting.awesome': '{name}, אתה פשוט מדהים! 💪',
    'pet.greeting.mission': 'בוא נכבוש את המשימה הבאה ביחד!',
    'pet.greeting.believe': 'אני מאמין בך, {name}! 🌟',
    'pet.skin.dragon': 'דרקון',
    'pet.skin.robot': 'רובוט',
    'pet.skin.cat': 'חתול',
    'pet.skin.fox': 'שועל',
    'pet.skin.unicorn': 'חד קרן',
    'pet.skin.owl': 'ינשוף',
    'pet.skin.bear': 'דוב',
    'pet.skin.dino': 'דינוזאור',
    
    // Navigation tabs
    'nav.tasks': 'משימות',
    'nav.timetable': 'מערכת',
    'nav.progress': 'התקדמות',
    'nav.store': 'חנות',
    'nav.settings': 'הגדרות',
    
    // Focus Fuel
    'fuel.charging': 'רמת מיקוד: נטען...',
    'fuel.halfway': 'חצי דרך! מצוין!',
    'fuel.almostFull': 'כמעט שם! המשך כך!',
    'fuel.full': 'טעון במלואו! זמן להפסקה?',
    'fuel.skillBadge': 'תג כישורים',
    'fuel.buffs': 'באפים',
    'fuel.dailyReset': 'המד מתאפס כל בוקר - כל יום הוא התחלה חדשה!',
    'fuel.offDay': '🌴 יום חופש',
    'fuel.schoolDay': '📚 יום לימודים',
    'fuel.goal': 'יעד',
    'fuel.goalOf': 'מ-',
    
    // Progress (legacy)
    'progress.dailyXP': 'XP יומי',
    'progress.levelComplete': 'הרמה הושלמה! 🎉',
    'progress.keepGoing': 'המשך להתחזק!',
    'progress.level': 'רמה',
    'progress.maxLevel': 'רמה מקסימלית!',
    
    // Focus Mode
    'focus.active': '🎯 מצב מיקוד פעיל',
    'focus.completeFirst': 'סיים את המשימה הזו לפני שתמשיך הלאה',
    'focus.allComplete': 'כל המשימות הושלמו!',
    'focus.greatWork': 'עבודה מצוינת! אתה יכול לעבור לשלב הבא.',
    'focus.remaining': 'משימות נותרו',
    
    // Common
    'common.loading': 'טוען...',
    'common.loadingDataFor': 'טוען נתונים עבור',
    'common.child': 'ילד',
    'common.error': 'שגיאה',
    'common.success': 'הצלחה',
    'common.confirm': 'אישור',
    'common.delete': 'מחק',
    'common.edit': 'ערוך',
    'common.add': 'הוסף',
    'common.close': 'סגור',
    'common.credits': 'קרדיטים',
    'common.xp': 'XP',
    'common.backToTasks': 'חזרה למשימות',
    'tasks': 'משימות',
    'noTasksForPhase': 'אין משימות לשלב הזה',
    
    // Legal
    'legal.title': 'הבהרה משפטית',
    'legal.disclaimer': 'הבהרה חשובה: האפליקציה Buff היא כלי טכנולוגי לניהול משימות והתארגנות, שפותח על בסיס ניסיון אישי וכלים מעולם ניהול המוצר וההורות. השימוש באפליקציה, ובכלל זה ה"תובנות" המופיעות בה, נועד למטרות העשרה וסיוע בלבד ואינו מהווה תחליף לייעוץ רפואי, פסיכולוגי, אבחוני או טיפולי מקצועי. יוצרת האפליקציה אינה מטפלת מוסמכת, רופאה או פסיכולוגית. בכל שאלה הנוגעת לבריאותו הגופנית או הנפשית של ילדכם, יש להיוועץ באנשי מקצוע מוסמכים. השימוש באפליקציה הוא באחריות המשתמש בלבד.',
    'legal.termsLink': 'תנאי השימוש וההבהרה המשפטית',
    'legal.footerLink': 'הבהרה משפטית',
    'legal.consentText': 'בעצם ההתחברות אני מאשר את',
    
    // Welcome Banner
    'welcome.title': 'ברוכים הבאים ל-BUFF',
    'welcome.message': 'הכנו לך כמה משימות התחלתיות לשגרה היומית. אתה יכול להתאים אותן בכל עת דרך ההגדרות!',
    'welcome.tasksReady': '✨ 8 משימות מוכנות ומחכות לך!',
    'welcome.letsGo': 'בוא נתחיל!',

    // Phase Transition Banner
    'phase.schoolEnded': '🎉 יום הלימודים הסתיים!',
    'phase.switchToAfternoon': 'עוברים למשימות צהריים',
    'phase.schoolStarted': '📚 הגיע הזמן ללימודים!',
    'phase.switchToSchool': 'עוברים ליום לימודים',
    'phase.transition': 'מעבר שלב',

    // New Day Banner
    'newDay.title': 'בוקר טוב!',
    'newDay.subtitle': 'המשימות החדשות מוכנות. יום חדש, הזדמנויות חדשות! 🚀',

    // Birthday Celebration
    'birthday.title': '🎉 יום הולדת שמח! 🎉',
    'birthday.forYou': 'לך!',
    'birthday.years': 'שנים!',
    'birthday.wish': 'שיהיה לך יום מדהים מלא בשמחה והצלחות! ✨',
    'birthday.thanks': 'תודה! 🥳',

    // Pack Completion Celebration
    'celebration.greatJob': 'כל הכבוד!',
    'celebration.champ': 'אלוף/ה',
    'celebration.focusMuscles': 'השתמשת בשרירי הריכוז שלך היום! 💪',
    'celebration.effortMessage': 'הרווחת את זה דרך העבודה הקשה שלך!',
    'celebration.creditsEarned': 'קרדיטים שנצברו',
    'celebration.continue': 'המשך להתקדם! 🚀',

    // Parent Daily Win Card
    'dailyWin.title': 'ניצחון יומי!',
    'dailyWin.completedTasks': 'השלים/ה {count} מתוך {total} משימות',
    'dailyWin.momentum': 'מומנטום יומי',
    'dailyWin.coachingTitle': 'רגע אימון',
    'dailyWin.coachingTip': '{name} סיים/ה את המשימות! זה הזמן לתת חיבוק ארוך או מחמאה ספציפית על המאמץ.',
    'dailyWin.viewInsight': 'צפה בתובנה מעמיקה',

    // View As Child Banner
    'viewAsChild.viewing': 'צפייה כ-',
    'viewAsChild.backToParent': 'חזרה להורה',

    // Gear Master
    'gear.nightMission': 'משימת ערב - בונוס מוכנות!',
    'gear.morningReminder': 'תזכורת בוקר - בדיקת תיק',
    'gear.bagReady': 'התיק מוכן! ✨',
    'gear.prepTomorrow': 'סידור ציוד למחר עכשיו',
    'gear.checkBag': 'בדיקה שהכל בתיק לפני היציאה',
    'gear.tomorrowOff': 'מחר יום חופש! 🎉',
    'gear.noScheduleTomorrow': 'אין מערכת למחר 📋',
    'gear.noBagPrep': 'אין צורך להכין תיק - תהנה מהמנוחה!',
    'gear.addSchedule': 'הוסיפו מערכת שעות דרך הגדרות ההורה כדי להפעיל את משימת הערב.',
    'gear.nightCompleted': 'משימת ערב - הושלמה! 🌟',
    'gear.bagReadyCredits': 'התיק מוכן למחר - נצברו',
    'gear.noSpecialEquipment': 'אין ציוד מיוחד נדרש',
    'gear.bagComplete': 'סידור תיק הושלם!',
    'gear.credits': 'קרדיטים',
    'gear.nightMissionComplete': '🎒 משימת הערב הושלמה!',
    'gear.nightMissionCompleteDesc': 'מעולה! סידור התיק מראש הביא',
    'gear.undo': 'בטל (5 שניות)',
    'gear.undone': '↩️ בוטל',
    'gear.undoneDesc': 'משימת הערב בוטלה',
    'gear.markAll': 'סימון כל הפריטים',
    'gear.itemsReady': 'פריטים מוכנים',
    'gear.eveningPrep': '🧹 הכנות ערב:',
    'gear.equipmentNeeded': '🎒 ציוד נדרש לשיעורים:',
    'gear.lunchboxReset': 'איפוס יומי: פינוי וניקוי תיק האוכל (קופסה למדיח/פח)',
    'gear.prepNow': 'סידור ציוד עכשיו!',
    'gear.noPoints': 'ללא נקודות',
    'gear.morningCheck': 'בדיקה שהכל בתיק לפני היציאה!',
    'gear.morningTip': '💡 טיפ: סידור תיק בערב הקודם מזכה בנקודות!',
    'gear.equipmentRequired': 'ציוד נדרש',

    // Daily Essentials
    'essentials.title': 'לפני היציאה מהבית',
    'essentials.noPoints': 'ללא נקודות',
    'essentials.allReady': 'הכל מוכן ליציאה! 🚀',
    'essentials.waterBottle': 'בקבוק מים',
    'essentials.food': 'אוכל/כריך',
    'essentials.phone': 'טלפון',
    'essentials.keys': 'מפתחות',

    // My Progress
    'myProgress.title': 'ההתקדמות שלי',
    'myProgress.weeklySummary': 'סיכום שבועי',
    'myProgress.weeklyMomentum': 'מומנטום שבועי',
    'myProgress.noActiveTasks': 'אין משימות פעילות כרגע',
    'myProgress.rechargeTime': 'זמן מצוין להטעין מצברים! 🔋✨',
    'myProgress.outOf7': 'מתוך 7 ✓',

    // Weekly Goal Ring
    'weeklyGoal.title': 'יעד שבועי',
    'weeklyGoal.outOf': 'מתוך',
    'weeklyGoal.perfect': '🏆 מושלם!',
    'weeklyGoal.goalReached': '🎯 הגעת ליעד!',
    'weeklyGoal.almostThere': '💪 כמעט שם!',
    'weeklyGoal.keepGoing': '🚀 המשך/י כך!',
    'weeklyGoal.progress': 'התקדמות',
    'weeklyGoal.goal70': 'יעד 70%',

    // Ticket Wallet
    'tickets.title': 'ארנק כרטיסים',
    'tickets.available': 'זמינים',
    'tickets.rest': 'מנוחה',
    'tickets.none': '😴 אין כרטיסי מנוחה זמינים',
    'tickets.oneLeft': '🌟 נשאר כרטיס מנוחה אחד!',
    'tickets.multiple': '✨ יש לך כרטיסי מנוחה',
    'tickets.infoTitle': 'איך עובדים כרטיסי מנוחה?',
    'tickets.rule1': 'כל',
    'tickets.rule1Tasks': '5 משימות',
    'tickets.rule1End': 'שהשלמת בהצלחה מזכות אותך בכרטיס מנוחה אחד.',
    'tickets.rule2': 'אפשר להשתמש בכרטיס כדי',
    'tickets.rule2Skip': '"לדלג"',
    'tickets.rule2End': 'על יום בלי לפגוע במטרה השבועית שלך (ה-70%).',
    'tickets.rule3': 'מנוחה היא חלק מהאימון! 💪',
    'tickets.rule3Tip': 'השתמש בהם בחוכמה בימים עמוסים.',
    'tickets.gotIt': 'הבנתי! 🚀',

    // School Day Section
    'school.equipmentRequired': 'ציוד נדרש',
    
    // DailySchedule
    'schedule.todaysSchedule': 'מערכת שעות להיום',
    'schedule.weekend': 'סוף שבוע - אין שיעורים',
    'schedule.enjoyWeekend': '🎉 שבת שלום!',
    'schedule.noSubjects': 'לא נקבעו מקצועות',
    'schedule.setupTimetable': 'הגדירו מערכת שעות דרך ממשק ההורה כדי לראות את לוח הזמנים.',
    'schedule.lessons': 'שיעורים',
    'schedule.period': 'שיעור',
    'schedule.now': 'עכשיו',

    // Timetable (WeeklyTimetable)
    'timetable.lessons': 'שיעורים',
    'timetable.plannedLessons': 'שיעורים מתוכננים',
    'timetable.add': '+ הוסף',
    'timetable.editAll': 'ערוך הכל',
    'timetable.noLessons': 'אין שיעורים ליום זה',
    'timetable.addFirst': '+ הוסף שיעור ראשון',
    'timetable.weekOverview': 'סקירת השבוע',
    'timetable.time': 'שעה',
    'timetable.subjectPlaceholder': 'שם המקצוע',
    'timetable.equipmentRequired': 'ציוד נדרש',
    'timetable.equipmentPlaceholder': 'מחברת, ספר לימוד...',
    'timetable.clickToAdd': 'לחצו להוספת מקצוע...',

    // TomorrowsPrep
    'prep.tomorrowOff': 'מחר יום חופש! 🎉',
    'prep.noBagPrep': 'אין צורך להכין תיק - תהנה מהמנוחה!',
    'prep.prepForTomorrow': 'הכנה למחר',
    'prep.noSpecialEquipment': 'לא הוגדר ציוד מיוחד למחר',
    'prep.equipmentChecklist': 'צ\'קליסט ציוד',
    'prep.bagReady': 'הכנת את התיק? מעולה! יום מחר יהיה קל יותר 💪',

    // Brand Terminology (Buff Positive Coaching DNA)
    'brand.holdingSpace': 'הכלה',
    'brand.boundaries': 'גבולות',
    'brand.strategies': 'כלים',
    'brand.coaching': 'אימון',
    'brand.readiness': 'בשלות',
    'brand.positiveReinforcement': 'חיזוק חיובי',

    // Parent Settings
    'parentSettings.title': 'הגדרות',
    'parentSettings.buffSettings': 'הגדרות Buff',
    'parentSettings.editTasksRewards': 'עריכת משימות, מערכת ופרסים',
    'parentSettings.generalAndChildren': 'הגדרות כלליות וניהול ילדים',
    'parentSettings.back': 'חזרה',
    'parentSettings.generalSettings': 'הגדרות כלליות',
    'parentSettings.familyDefaults': 'הגדרות ברירת מחדל למשפחה',
    'parentSettings.appName': 'שם האפליקציה',
    'parentSettings.lessonReminders': 'תזכורות שיעורים',
    'parentSettings.updatesFromAdi': 'עדכונים וטיפים מעדי',
    'parentSettings.weekendTips': 'טיפים לסופ"ש ופיצ\'רים חדשים',
    'parentSettings.subscribedUpdates': 'נרשמת לעדכונים!',
    'parentSettings.unsubscribedUpdates': 'בוטלה ההרשמה לעדכונים',
    'parentSettings.settingsError': 'שגיאה בעדכון ההגדרות',
    'parentSettings.childManagement': 'ניהול ילדים',
    'parentSettings.noChildrenYet': 'עדיין לא הצטרפו ילדים',
    'parentSettings.learningGuidance': 'למידה והדרכה',
    'parentSettings.understandApproach': 'הבנת הגישה מאחורי Buff',
    'parentSettings.worldView': 'תפיסת העולם',
    'parentSettings.about': 'אודות',
    'parentSettings.signOutAccount': 'התנתק מהחשבון',
    'parentSettings.personalBuffSettings': 'הגדרות Buff אישיות',
    'parentSettings.balance': 'יתרה',
    'parentSettings.dailyGoal': 'יעד יומי',
    'parentSettings.birthDate': 'ת.לידה',
    'parentSettings.schoolQuest': 'School Quest',
    'parentSettings.nightMissionBonus': 'משימת ערב - בונוס מוכנות',
    'parentSettings.buffPoints': 'נקודות Buff',
    'parentSettings.tasks': 'משימות',
    'parentSettings.schedule': 'מערכת',
    'parentSettings.rewards': 'פרסים',
    'parentSettings.uploadSchedule': 'העלאת מערכת',
    'parentSettings.manageScheduleEquipment': 'ניהול מערכת וציוד',
    'parentSettings.lessonsConfigured': 'שיעורים מוגדרים',
    'parentSettings.editRewardsStore': 'ערוך חנות פרסים',
    'parentSettings.noRewardsConfigured': 'אין פרסים מוגדרים',
    'parentSettings.clickToAdd': 'לחץ על "ערוך חנות פרסים" להוספה',
    'parentSettings.sold': 'נמכר',
    'parentSettings.deleteChild': 'מחיקת ילד',
    'parentSettings.deleteProfileAndData': 'מחיקת הפרופיל וכל הנתונים',
    'parentSettings.deleteConfirm': 'מחיקת',
    'parentSettings.deleteWarning': 'פעולה זו תמחק את כל המשימות, הנקודות והפרסים של הילד. לא ניתן לבטל פעולה זו.',
    'parentSettings.delete': 'מחק',
    'parentSettings.cancel': 'ביטול',
    'parentSettings.deletedSuccess': 'נמחק בהצלחה',
    'parentSettings.deleteError': 'שגיאה במחיקת הילד',
    'parentSettings.avatarUpdated': 'האווטאר עודכן!',
    'parentSettings.avatarError': 'שגיאה בעדכון האווטאר',
    'parentSettings.balanceUpdated': 'היתרה עודכנה בהצלחה!',
    'parentSettings.balanceError': 'שגיאה בעדכון היתרה',
    'parentSettings.invalidBalance': 'אנא הזן יתרה תקינה (0 עד 1,000,000)',
    'parentSettings.goalUpdated': 'היעד עודכן בהצלחה!',
    'parentSettings.goalError': 'שגיאה בעדכון היעד',
    'parentSettings.invalidGoal': 'אנא הזן יעד תקין (10 עד 1000)',
    'parentSettings.birthDateSaved': 'תאריך הלידה נשמר!',
    'parentSettings.birthDateError': 'שגיאה בשמירת תאריך הלידה',
    'parentSettings.bagPrepCreditsUpdated': 'קרדיטים להכנת תיק עודכנו!',
    'parentSettings.bagPrepCreditsError': 'שגיאה בעדכון',
    'parentSettings.invalidBagPrepCredits': 'אנא הזן כמות תקינה (5 עד 100)',
    'parentSettings.schoolQuestActivated': 'הפעלת את מודול School Quest! 🎓',
    'parentSettings.schoolQuestActivatedDesc': 'עכשיו, מלא את מערכת השעות כדי לעזור לילד לקבל Buff במיקוד בבית הספר!',
    'parentSettings.schoolQuestTipTitle': 'הפעלת את School Quests! 🎓',
    'parentSettings.schoolQuestTipDesc': 'מלא מערכת שעות למיקוד בביה"ס',
    'parentSettings.whyTimetable': '💡 למה מערכת שעות?',
    'parentSettings.timetableExplanation': 'מערכת השעות עוזרת לילד לעקוב אחרי רגעי הצלחה בלמידה קשובה ולזהות מתי קשה יותר להתרכז. זה כלי למודעות עצמית, לא לביקורת.',
    'parentSettings.schoolQuestDisabledWarning': '⚠️ כרגע ״משימת בית הספר״ כבויה - המערכת לא תוצג לילד. הפעילו אותה בהגדרות למעלה.',
    'parentSettings.fridayAutoEnabled': 'יום שישי הופעל אוטומטית כי המערכת מכילה שיעורים ביום שישי',
    'parentSettings.taskUpdated': 'המשימה עודכנה בהצלחה',
    'parentSettings.addTask': 'הוסף משימה',
    'parentSettings.taskName': 'שם המשימה',
    'parentSettings.activeDays': 'ימים פעילים',
    'parentSettings.additionalDetails': 'פרטים נוספים או ציוד (אופציונלי)',
    'parentSettings.detailsPlaceholder': 'למשל: להביא תיקיית אומנות, לא לשכוח בקבוק מים...',
    'parentSettings.save': 'שמור',
    'parentSettings.noTasksYet': 'אין משימות עדיין',
    'parentSettings.credits': 'קרדיטים',
    'parentSettings.copyToChild': 'העתק לילד אחר',
    'parentSettings.taskCopied': 'המשימה הועתקה',
    'parentSettings.rewardCopied': 'הפרס הועתק',
    'parentSettings.toChildren': 'ילדים',
    'parentSettings.copyError': 'שגיאה בהעתקה',
    'parentSettings.noFamilyFound': 'לא נמצאה משפחה',
    'parentSettings.childAddedSuccess': 'נוסף בהצלחה! 🎉',
    'parentSettings.childCreateError': 'שגיאה ביצירת פרופיל הילד',

    // Category options
    'category.learning': 'למידה',
    'category.organization': 'התארגנות',
    'category.selfCare': 'טיפול עצמי',
    'category.responsibility': 'בית ואחריות',
    'category.movement': 'גוף ותנועה',

    // Parent Bottom Navigation
    'parentNav.monitoring': 'מעקב',
    'parentNav.settings': 'הגדרות',
    'parentNav.reports': 'דוחות',
    'parentNav.viewAsChild': 'צפה כילד',

    // Parent Family Overview
    'overview.familyOverview': 'סקירה משפחתית',
    'overview.realTimeTracking': 'מעקב התקדמות בזמן אמת',
    'overview.now': 'עכשיו',
    'overview.morning': 'בוקר',
    'overview.school': 'בית ספר',
    'overview.afternoon': 'אחר הצהריים',
    'overview.evening': 'ערב',
    'overview.myChildren': 'הילדים שלי',
    'overview.creditsAccumulated': 'קרדיטים נצברו',
    'overview.outOf': 'מתוך',
    'overview.todayProgress': 'התקדמות היום',
    'overview.tasks': 'משימות',
    'overview.lessons': 'שיעורים',
    'overview.awardingBonus': 'מעניק בונוס...',
    'overview.bonusAwarded': 'בונוס יום מוצלח ניתן ✓',
    'overview.greatDay': '🌟 יום מוצלח במיוחד! (+20)',
    'overview.viewAsChild': 'צפה כילד',

    // Parent View
    'parentView.loading': 'טוען...',
    'parentView.child': 'ילד',
    'parentView.addChildTitle': 'הוספת ילד חדש',

    // Welcome Home Screen
    'welcome.addFirstChild': 'הוסיפו את הילד הראשון שלכם',
    'welcome.startJourney': 'כדי להתחיל במסע המשותף',
    'welcome.connectChildForInsights': 'חברו ילד כדי לפתוח תובנות אלו',
    'welcome.weeklySuccess': 'אחוז הצלחה שבועי',
    'welcome.insightsComingSoon': 'תובנות והתקדמות - בקרוב אצלכם',

    // First Task Nudge Card
    'nudge.readyToStart': 'היי {name}, מוכנים להתחיל?',
    'nudge.profileSetup': 'הגדרנו את הפרופיל, עכשיו רק נשאר לבחור את המשימה הראשונה כדי להתחיל לצבור נקודות.',
    'nudge.addFirstTask': 'הוספת משימה ראשונה',

    // Setup Progress Header
    'setup.almostDone': 'נשאר רק עוד קצת כדי להשלים את הגדרת BUFF',
    'setup.missing': 'חסר',
    'setup.addChild': 'הוספת ילד',
    'setup.configureTasks': 'הגדרת משימות',
    'setup.configureRewards': 'הגדרת פרסים',
    'setup.timetable': 'מערכת שעות',

    // Parent Welcome Banner
    'parentWelcome.title': 'ברוכים הבאים ל-Buff',
    'parentWelcome.noChildrenMsg': 'מוכנים להתחיל? נעזור לכם להגדיר את הפרופיל הראשון של הילד, המשימות והפרסים תוך 2 דקות.',
    'parentWelcome.hasChildrenMsg': 'הכנו עבורכם את התשתית המקצועית ביותר לניהול היום. מומלץ להתחיל בקריאת "תפיסת העולם" שלנו כדי להפיק את המקסימום מהתהליך.',
    'parentWelcome.letsStart': 'בואו נתחיל! 🚀',
    'parentWelcome.readFirst': 'קודם אקרא על השיטה',
    'parentWelcome.learnMore': 'למדו עוד על השיטה',
    'parentWelcome.skipStart': 'דלג, אתחיל לבד',

    // Parent Reports
    'reports.title': 'Weekly Buff Stats',
    'reports.analysis': 'ניתוח ותובנות',
    'reports.weeklyAnalysis': 'ניתוח ותובנות שבועיות',
    'reports.loadingReports': 'טוען דוחות...',
    'reports.noChildrenYet': 'אין עדיין ילדים לניתוח',
    'reports.loadingInsights': 'טוען תובנות...',
    'reports.selectChild': 'בחר ילד',
    'reports.phasePerformance': 'ביצועים לפי שלב',
    'reports.strong': 'חזק',
    'reports.igniting': 'בהתנעה',
    'reports.bySubject': 'לפי מקצוע',
    'reports.insightsFor': 'תובנות ל-',
    'reports.noInsightsYet': 'אין עדיין תובנות. בדקו שוב אחרי מספר ימי פעילות.',
    'reports.showLess': 'הצג פחות',
    'reports.more': 'עוד',
    'reports.difficulty': 'קושי',
    'reports.general': 'כללי',
    'reports.fridaySchoolDay': 'יום שישי יום לימודים',
    'reports.buffPoints': 'נקודות באף',
    'reports.streak': 'רצף',
    'reports.quests': 'משימות',
    'reports.lessons': 'שיעורים',
    'reports.trendDetector': 'גלאי מגמות',
    'reports.reflectionLog': 'יומן רפלקציה',

    // Ignition Insights
    'ignition.weeklyAnalysis': 'ניתוח הצתה שבועי',
    'ignition.ignitionAnalysis': 'Ignition Analysis',
    'ignition.weeklyRate': 'שיעור ההצתה השבועי',
    'ignition.goal70': 'יעד 70%',
    'ignition.aboveGoal': 'מעל סף ההצלחה של 70%!',
    'ignition.onTheWay': 'בדרך הנכונה - עוד קצת ומגיעים ל-70%!',
    'ignition.ignitedDays': 'ימי הצתה 🔥',
    'ignition.chargingDays': 'ימי טעינה 🔋',
    'ignition.strongestCategory': 'הקטגוריה הכי חזקה',
    'ignition.success': 'הצלחה',
    'ignition.mostActiveWindow': 'חלון הזמן הפעיל ביותר',
    'ignition.positiveReinforcement': 'רגע חיזוק חיובי',
    'ignition.weeklyMap': 'מפת הצתה שבועית',
    'ignition.ignitedDay': 'יום הצתה',
    'ignition.chargingDay': 'יום טעינה',
    'ignition.days': 'ימים',
    'ignition.actionSuggestion': 'הצעה לפעולה',
    'phase.morning': 'בוקר',
    'phase.school': 'בי״ס',
    'phase.afternoon': 'צהריים',
    'phase.evening': 'ערב',
    'phase.tasks': 'משימות',
    'day.sun': 'ראשון',
    'day.mon': 'שני',
    'day.tue': 'שלישי',
    'day.wed': 'רביעי',
    'day.thu': 'חמישי',
    'day.fri': 'שישי',
    'day.sat': 'שבת',

    // Help Section
    'help.title': 'עזרה והתקנה',
    'help.subtitle': 'סרטון הדרכה ושיתוף לילדים',
    'help.videoFallback': 'הדפדפן שלכם לא תומך בווידאו',
    'help.videoLabel': 'סרטון הדרכה קצר - איך להתקין את BUFF',
    'help.shareInstallGuide': 'שלח מדריך התקנה לילד:',
    'help.shareMessage': 'צפו בסרטון הקצר כדי להתקין את BUFF על הטלפון 📱',
    'help.shareSubject': 'התקנת BUFF',
    'help.email': 'אימייל',
    'help.copyLink': 'העתק לינק',
    'help.copied': 'הועתק!',
    'help.linkCopied': 'הלינק הועתק!',
    'help.copyError': 'שגיאה בהעתקה',

    // Join Family
    'joinFamily.title': 'הצטרפות למשפחה',
    'joinFamily.subtitle': 'הצטרפו למשפחה קיימת עם קוד משפחה',
    'joinFamily.codeLabel': 'קוד משפחה (6 תווים)',
    'joinFamily.codeError6': 'קוד משפחה חייב להכיל 6 תווים',
    'joinFamily.codeErrorAlphanumeric': 'קוד משפחה חייב להכיל אותיות ומספרים בלבד',
    'joinFamily.joinError': 'שגיאה בהצטרפות למשפחה',
    'joinFamily.invalidCode': 'קוד לא תקין, אנא ודאו שזה הקוד המופיע במכשיר של בן/בת הזוג',
    'joinFamily.success': 'הצטרפת למשפחה בהצלחה!',
    'joinFamily.joining': 'מצטרף...',
    'joinFamily.join': 'הצטרף למשפחה',
    'joinFamily.hint': 'בקשו מבן/בת הזוג את קוד המשפחה מההגדרות שלהם',

    // Duplicate Modal
    'duplicate.copyTask': 'העתק משימה',
    'duplicate.copyReward': 'העתק פרס',
    'duplicate.copying': 'העתקת:',
    'duplicate.noOtherChildren': 'אין ילדים נוספים במשפחה',
    'duplicate.addChildHint': 'הוסיפו ילד נוסף כדי להשתמש בפיצ\'ר הזה',
    'duplicate.allChildren': 'לכל הילדים',
    'duplicate.copy': 'העתק',
    'duplicate.cancel': 'ביטול',

    // Philosophy Page
    'philosophy.title': 'תפיסת העולם של Buff',
    'philosophy.subtitle': 'מדריך מקצועי להורים - הפילוסופיה מאחורי המערכת',
    'philosophy.share': 'שתף',
    'philosophy.back': 'חזרה',
    'philosophy.fromParents': 'מהורים להורים',
    'philosophy.intro': 'אנחנו יודעים כמה מאתגר לגדל ילד עם קשיי קשב וריכוז. הכנו עבורכם מדריך שמסביר את הגישה המקצועית שמאחורי Buff - מערכת שנבנתה בשיתוף פעולה עם מומחים בתחום, מבוססת על עקרונות לחיזוק תפקודים ניהוליים שהוכחו מחקרית.',
    'philosophy.buffInsight': 'תובנת Buff',
    'philosophy.letsStart': 'הבנתי, בואו נתחיל!',
    'philosophy.tip': '💡 טיפ: שתפו את העמוד הזה עם בני זוג, מורים, או מטפלים - כדי שכולם יבינו את הגישה וידעו לתמוך בילד בצורה עקבית.',
    'philosophy.readStory': 'קראו את הסיפור מאחורי Buff',
    'philosophy.branding.title': 'השם Buff - העצמה ושדרוג יכולות',
    'philosophy.branding.subtitle': 'לא עוד רשימת מטלות - אלא כלי להעצמה',
    'philosophy.branding.content': 'במשחקי וידאו, "Buff" הוא בונוס שמחזק את הדמות באופן זמני ומאפשר לה להתמודד עם אתגרים שנראו בלתי אפשריים. זה בדיוק מה שאנחנו רוצים לתת לילד שלכם.\n\nBuff היא לא עוד אפליקציה לניהול משימות. היא מערכת העצמה שמדברת בשפה שהילדים מבינים ואוהבים. הילדים שלכם לא "מסמנים משימות" - הם "משלימים קווסטים" וצוברים "Buff Points" לתוך "הכספת" (The Vault).\n\nהשפה הזו אינה גימיק - היא יוצרת חיבור רגשי עמוק והופכת את השגרה המאתגרת להרפתקה שהילד רוצה להיות חלק ממנה.',
    'philosophy.branding.insight': 'מחקרים בתחום התפקודים הניהוליים מלמדים שמוטיבציה פנימית נבנית כאשר הפעילות מרגישה משמעותית ומהנה לילד עצמו. שפת גיימינג מוכרת ממזערת התנגדות ומגבירה מעורבות אצל ילדים עם קשיי קשב וריכוז.',
    'philosophy.rewards.title': 'אסטרטגיית הפרסים - גשר הדופמין',
    'philosophy.rewards.subtitle': 'פרסים מדורגים לפי "ימי הצלחה" (1, 2, 4, 5, 10)',
    'philosophy.rewards.content': 'עבור מוח עם ADHD, העתיד הרחוק הוא מופשט ולא מוחשי. פרסים גדולים "בעוד חודש" אינם מניעים - הם מרגישים כמו נצח.\n\nלכן, בנינו מערכת פרסים מדורגת לפי "ימי הצלחה":\n\n📱 יום אחד (1x יעד חכם) - תוספת זמן מסך או בחירת קינוח\n🎉 יומיים (2x יעד חכם) - פטור ממטלה מעצבנת אחת\n🎬 ארבעה ימים (4x יעד חכם) - ערב סרט ופופקורן\n🍕 חמישה ימים (5x יעד חכם) - ערב פיצה או סושי\n🎢 עשרה ימים (10x יעד חכם) - יום כיף\n\nהשיטה הזו יוצרת "גשר דופמין" - פרסים קטנים ונגישים כל יומיים בונים התמדה וביטחון עצמי, בעוד הפרסים הגדולים מלמדים דחיית סיפוקים בצורה הדרגתית.',
    'philosophy.rewards.insight': 'מחקרים מראים שילדים עם ADHD מגיבים טוב יותר לחיזוקים מיידיים וקרובים. פרסים קטנים ותכופים יעילים יותר מפרס גדול אחד רחוק. השילוב של שני הסוגים בונה גם מוטיבציה מיידית וגם יכולת לדחיית סיפוקים.',
    'philosophy.positive.title': 'חיזוקים חיוביים בלבד - נמל מבטחים',
    'philosophy.positive.subtitle': 'יצירת סביבה בטוחה ללא עונשים או הפחתות',
    'philosophy.positive.content': 'אנחנו יודעים כמה קשה לראות את הילד מתמודד עם תסכול. לכן בנינו מערכת שיוצרת "נמל מבטחים" רגשי - מקום בו הילד לא יכול להפסיד.\n\nבמערכת Buff, הילד יכול רק להרוויח נקודות - לעולם לא להפסיד אותן. אין נקודות שליליות, אין הורדות, אין עונשים. כשמשימה לא הושלמה, היא פשוט לא צברה נקודות - וזהו.\n\nלמה זה כל כך חשוב? כי ילדים עם ADHD חווים יותר ביקורת ותיקונים מאחרים. הם צריכים מרחב בו הם יכולים לנסות, להיכשל, ולנסות שוב - בלי פחד מעונש.\n\nההתמקדות תמיד במה שכן הושג. זה מפחית התנגדויות ובונה ביטחון עצמי.',
    'philosophy.positive.insight': 'מחקרים מראים שילדים עם ADHD מגיבים טוב יותר לחיזוק חיובי מאשר לעונשים. חיזוק שלילי יוצר חרדה ונמנעות, בעוד חיזוק חיובי בונה ביטחון עצמי ומוטיבציה פנימית לטווח ארוך.',
    'philosophy.bonus.title': 'בונוס הורה - הכרה במאמץ השקוף',
    'philosophy.bonus.subtitle': 'כלי לזיהוי העבודה הקשה שלא תמיד נראית',
    'philosophy.bonus.content': 'אנחנו יודעים שהרבה מהמאמץ של הילד שלכם הוא "שקוף" - הוא לא נראה לעין. להתגבר על הדחף לקום מהכיסא, להתאפק מלהגיב, להישאר ממוקד - כל אלה דורשים מאמץ עצום שלא מתועד במשימות.\n\nלכן נתנו לכם כלי ייחודי: "בונוס יום מוצלח" - 20 Buff Points שאתם מעניקים לילד פעם ביום, לפי שיקול דעתכם.\n\nזה לא אוטומטי. זו החלטה מודעת שלכם להגיד לילד: "ראיתי את המאמץ שלך היום".\n\nהבונוס הזה יוצר הזדמנות לשיחה חיובית, מחזק את הקשר בינכם, ומלמד את הילד שמאמץ מוערך - גם כשהתוצאות לא מושלמות. זו גם הזדמנות להפגין גמישות כהורים.',
    'philosophy.bonus.insight': 'אינטראקציה חיובית בין הורה לילד היא מרכיב קריטי בפיתוח תפקודים ניהוליים. הבונוס משמש כ"גשר רגשי" ומחזק את תחושת ה-Agency של הילד - ההרגשה שהוא יכול להשפיע על מציאות חייו.',
    'philosophy.dayTypes.title': 'סוגי ימים - ניהול אנרגיה ומניעת שחיקה',
    'philosophy.dayTypes.subtitle': 'התאמה אוטומטית בין יום לימודים ליום מנוחה',
    'philosophy.dayTypes.content': 'ילדים עם ADHD צורכים יותר אנרגיה מנטלית במהלך היום. הם "רצים מרתון כשאחרים רצים ספרינט". לכן חיוני להתאים את הציפיות לסוג היום.\n\nהמערכת מזהה אוטומטית אם זה "יום לימודים" (ראשון-חמישי) או "יום חופש" (שישי-שבת וחגים) ומתאימה את המשימות בהתאם:\n\n📚 יום לימודים - דגש על שגרת בוקר יעילה, הכנה לבית ספר, ושגרת ערב מרגיעה.\n\n🌴 יום חופש - דגש על מנוחה והתאוששות, עזרה בבית בקצב רגוע, וזמן ליצירתיות.\n\nההתאמה הזו מונעת שחיקה. היא מלמדת את הילד שגם מנוחה היא חלק מהתוכנית, ושציפיות משתנות בהתאם להקשר - שיעור חשוב לחיים.',
    'philosophy.dayTypes.insight': 'ילדים עם ADHD זקוקים למבנה יציב, אבל גם לגמישות מותאמת. היכולת לזהות "סוג יום" ולהתאים ציפיות מפחיתה עומס קוגניטיבי ומונעת את תחושת הכישלון שנובעת מציפיות לא ריאליסטיות.',
    'philosophy.smartGoal.title': 'יעד ה-70% - רצף ניצחונות',
    'philosophy.smartGoal.subtitle': 'בניית הצלחה על הצלחה',
    'philosophy.smartGoal.content': 'אחד הלקחים החשובים ביותר שלמדנו מעבודה עם ילדים עם ADHD הוא שיעדים גבוהים מדי הורסים מוטיבציה.\n\nלכן, במקום יעד קבוע של "100% מהמשימות", המערכת מחשבת אוטומטית יעד של 70% מסך הנקודות האפשריות ליום ספציפי.\n\nלמה דווקא 70%?\n• גבוה מספיק לאתגר את הילד\n• נמוך מספיק להיות מושג ביום רגיל\n• משאיר מרווח ל"ימים קשים" בלי להרגיש כישלון\n\nכשהילד מגיע ל-70%, הוא מרגיש הצלחה אמיתית. כשהוא עובר את ה-70%, הוא מרגיש שהוא "מנצח את המשחק".\n\nזה יוצר "רצף ניצחונות" (Winning Streak) שבונה ביטחון עצמי במקום לקבע תחושת כישלון כרונית.',
    'philosophy.smartGoal.insight': 'יעדים לא ריאליסטיים הם אחד הגורמים העיקריים לנשירה ממערכות התנהגותיות. כלל ה-70% מבוסס על עקרון "הצלחה בנויה על הצלחה" - כל הישג מחזק את המוטיבציה להמשך וגורם לילד לרצות להמשיך לנסות.',

    // Onboarding Steps
    'onboarding.step1.title': 'בואו נכיר את הגיבורים שלכם',
    'onboarding.step1.subtitle': 'מי מצטרף לנבחרת BUFF?',
    'onboarding.step1.childName': 'שם הילד/ה',
    'onboarding.step1.namePlaceholder': 'לדוגמה: נועם',
    'onboarding.step1.birthDate': 'תאריך לידה',
    'onboarding.step1.day': 'יום',
    'onboarding.step1.month': 'חודש',
    'onboarding.step1.year': 'שנה',
    'onboarding.step1.age': 'גיל',
    'onboarding.step1.years': 'שנים',
    'onboarding.step1.nameError': 'אנא הזינו את שם הילד/ה',
    'onboarding.step1.dateError': 'אנא בחרו תאריך לידה מלא',
    'onboarding.step1.ageError': 'הגיל צריך להיות בין 5 ל-25',
    'onboarding.step1.birthDateHelp': '💡 תאריך הלידה עוזר לנו להתאים את המשימות והשפה לשלב שבו הילדים נמצאים.',
    'onboarding.step1.cta': 'בואו נתחיל! 🚀',
    'onboarding.step1.back': 'חזרה',
    'onboarding.month.0': 'ינואר',
    'onboarding.month.1': 'פברואר',
    'onboarding.month.2': 'מרץ',
    'onboarding.month.3': 'אפריל',
    'onboarding.month.4': 'מאי',
    'onboarding.month.5': 'יוני',
    'onboarding.month.6': 'יולי',
    'onboarding.month.7': 'אוגוסט',
    'onboarding.month.8': 'ספטמבר',
    'onboarding.month.9': 'אוקטובר',
    'onboarding.month.10': 'נובמבר',
    'onboarding.month.11': 'דצמבר',

    // Step 2
    'onboarding.step2.title': 'מה המקום שהכי הייתם רוצים להצליח בו השבוע?',
    'onboarding.step2.subtitle': 'בחרו תחום אחד:',
    'onboarding.step2.homework': 'שיעורי בית ותרגול',
    'onboarding.step2.homeworkDesc': 'למידה ממוקדת והצלחה במשימות לימודיות.',
    'onboarding.step2.project': 'פרויקט אישי',
    'onboarding.step2.projectDesc': 'קידום תחביב, תכנות או חלום שלכם.',
    'onboarding.step2.fitness': 'כושר וספורט',
    'onboarding.step2.fitnessDesc': 'התמדה באימונים ובתנועה יומית.',
    'onboarding.step2.home': 'בית וארגון',
    'onboarding.step2.homeDesc': 'עצמאות וסדר בחדר ובחיי היומיום.',

    // Step 3
    'onboarding.step3.title': 'בחרו ערכת התחלה',
    'onboarding.step3.subtitle': 'כל ערכה כוללת משימות מוכנות ופרס מותאם:',
    'onboarding.step3.includes': '📦 כולל {n} משימות מוכנות + פרס מותאם',
    'onboarding.step3.mostPopular': 'הבחירה הנפוצה',
    'onboarding.step3.proPacks': 'ערכות פרימיום',
    'onboarding.step3.proDesc': 'פתחו מסלולים מיוחדים כמו ״חיית מחמד וירטואלית״ או ״מיומנויות חברתיות״ עם BUFF Pro.',
    'onboarding.step3.note': '💡 תמיד אפשר לשנות את הבחירה בהגדרות.',
    'onboarding.step3.cta': 'המשך',
    'onboarding.step3.upgradeToUnlock': '🔓 שדרגו ל-Pro כדי לפתוח',
    // Learning packs
    'onboarding.step3.pack.school_quest': 'קשב והשתתפות',
    'onboarding.step3.pack.school_quest.desc': 'הכנה לשיעור, הקשבה פעילה ורישום שיעורי בית. חוזר בכל שיעור.',
    'onboarding.step3.pack.homework_hero': 'שיעורי בית',
    'onboarding.step3.pack.homework_hero.desc': 'בדיקה, השלמה ומשימה אקדמית בונוס.',
    // Home packs
    'onboarding.step3.pack.morning_pro': 'התארגנות בוקר',
    'onboarding.step3.pack.morning_pro.desc': 'מוכן בזמן, צחצוח, ארוחת בוקר בריאה ותרופות.',
    'onboarding.step3.pack.evening_routine': 'שגרת ערב',
    'onboarding.step3.pack.evening_routine.desc': 'כיבוי מסכים, מקלחת וצחצוח, שינה בזמן.',
    // Fitness packs
    'onboarding.step3.pack.daily_dash': 'תנועה',
    'onboarding.step3.pack.daily_dash.desc': 'הליכה קצרה, ספורט קצר וספורט ארוך.',
    'onboarding.step3.pack.fuel_up': 'תדלוק נכון',
    'onboarding.step3.pack.fuel_up.desc': 'שתייה, חטיף בריא ומשחק ללא מסכים.',
    // Project packs
    'onboarding.step3.pack.steam_startup': 'STEAM / סטארטאפ משפחתי',
    'onboarding.step3.pack.steam_startup.desc': 'פרויקטים יצירתיים, מדע וטכנולוגיה — בקרוב!',
    // Pack task titles
    'pack.task.class_prep': 'הכנה לשיעור',
    'pack.task.active_listening': 'הקשבה פעילה',
    'pack.task.record_hw': 'רישום שיעורי בית',
    'pack.task.check_hw': 'בדיקה אם יש שיעורי בית',
    'pack.task.complete_hw': 'השלמת שיעורי בית',
    'pack.task.bonus_academic': 'משימה אקדמית בונוס',
    'pack.task.ready_on_time': 'מוכן בזמן',
    'pack.task.teeth_morning': 'צחצוח שיניים',
    'pack.task.healthy_breakfast': 'ארוחת בוקר בריאה',
    'pack.task.medication': 'תרופות',
    'pack.task.screens_off': 'כיבוי מסכים',
    'pack.task.shower_teeth': 'מקלחת וצחצוח',
    'pack.task.bed_on_time': 'שינה בזמן',
    'pack.task.short_walk': 'הליכה קצרה',
    'pack.task.short_sport': 'ספורט קצר',
    'pack.task.long_sport': 'ספורט ארוך',
    'pack.task.hydration': 'שתייה',
    'pack.task.healthy_snack': 'חטיף בריא',
    'pack.task.screen_free_play': 'משחק ללא מסכים',

    // Step 4
    'onboarding.step4.title': 'מנצחים את ה"התנעה" 🏁',
    'onboarding.step4.tip1': '<strong>קשה לצלול למשימה?</strong> קובעים רק 15 דקות.',
    'onboarding.step4.tip2': 'בוחרים משהו <strong>קטנטן</strong> שאפשר לסיים מהר.',
    'onboarding.step4.tip3': 'ברגע שמתחילים – <strong>הדופמין כבר יעשה את השאר!</strong>',
    'onboarding.step4.label': 'המשימה הראשונה שלי:',
    'onboarding.step4.placeholder': 'לדוגמה: לפתור תרגיל אחד',
    'onboarding.step4.defaultTask': 'לפתור תרגיל אחד',
    'onboarding.step4.hint': 'זו תהיה המשימה שתופיע ראשונה בדשבורד 🎯',
    'onboarding.step4.cta': 'המשך',

    // Step 5
    'onboarding.step5.title': 'הופכים מאמץ לכיף 🎮',
    'onboarding.step5.tip1': '<strong>כל צעד נחשב:</strong> על כל סימון ✓ במשימה צוברים נקודות.',
    'onboarding.step5.tip2': '<strong>המטרה:</strong> להפוך את המאמץ היומי לסיפוק מיידי.',
    'onboarding.step5.rewardIdeas': 'רעיונות לפרסים:',
    'onboarding.step5.label': 'פרס סוף השבוע שלנו:',
    'onboarding.step5.placeholder': 'לדוגמה: בילוי משותף או זמן מסך',
    'onboarding.step5.defaultReward': 'בילוי משותף',
    'onboarding.step5.cta': 'המשך',
    'onboarding.step5.reward1': '🎬 ערב סרט',
    'onboarding.step5.reward2': '🍕 פיצה',
    'onboarding.step5.reward3': '📱 זמן מסך',
    'onboarding.step5.reward4': '🎮 משחק חדש',

    // Step 6
    'onboarding.step6.title': 'הכל מוכן לשיגור! 🚀',
    'onboarding.step6.familyCode': 'הקוד המשפחתי שלכם:',
    'onboarding.step6.copied': 'הועתק ללוח! ✓',
    'onboarding.step6.copiedToast': 'הועתק! 📋',
    'onboarding.step6.copyError': 'לא הצלחנו להעתיק',
    'onboarding.step6.shareWhatsApp': 'שלחו ל{name} בוואטסאפ',
    'onboarding.step6.instructionsCopied': 'ההוראות הועתקו! 📋 עכשיו אפשר להדביק בוואטסאפ או בכל מקום אחר',
    'onboarding.step6.instructionsCopiedShort': 'ההוראות הועתקו! ✓',
    'onboarding.step6.copyInstructions': 'העתק הוראות חיבור (אם וואטסאפ לא נפתח)',
    'onboarding.step6.callToAction': 'זה הזמן לקרוא ל<strong>{name}</strong>, להוריד את BUFF במכשיר שלהם ולהזין את הקוד המשפחתי. המשימה הראשונה כבר מחכה בפנים!',
    'onboarding.step6.launchCta': 'זהו, אנחנו מחוברים! יוצאים לדרך ⚡',
    'onboarding.step6.creating': 'יוצרים את המשפחה...',
    'onboarding.step6.whatsappMessage': '🎮 היי {name}! הכל מוכן ב-BUFF!\n\n📱 איך להצטרף:\n1. היכנס/י לאפליקציה: {url}\n2. לחץ/י על "הרשמה"\n3. בחר/י "אני נער/ה"\n4. הזן/י את הקוד המשפחתי:\n\n🔑 {code}\n\nמחכים לך באפליקציה! 🚀',

    // Clean Day Bonus
    'bonus.alreadyAwarded': 'בונוס יום מוצלח כבר ניתן ל{name} היום!',
    'bonus.awarded': '🌟 {name} קיבל/ה בונוס יום מוצלח! +{credits} קרדיטים',
    'bonus.error': 'שגיאה בהענקת הבונוס',

    // Notifications
    'notification.lessonSoon': '🎯 שיעור {subject} מתחיל בעוד 5 דקות!',
    'notification.getReady': 'הגיע הזמן להתכונן! 🏆',
    'notification.gearMasterTitle': '🎒 משימת ערב - בונוס מוכנות!',
    'notification.gearMasterBody': 'התיק למחר כבר מוכן? זה הזמן לזכות ב-{credits} נקודות Buff! ✨',

    // Install Prompt Messages
    'install.personalized.0': 'הופכים את הבוקר של {names} לסיפור הצלחה. הוסיפו את Buff למסך הבית.',
    'install.personalized.1': 'כי ל-{names} מגיע להתחיל את היום בחיוך. שימו את Buff בקדמת המסך.',
    'install.personalized.2': 'מוכנים לבוקר רגוע עם {names}? התקינו את האפליקציה לגישה מהירה.',
    'install.personalized.3': 'הגשר של {names} לעצמאות מתחיל כאן. הוסיפו אותנו למסך הבית.',
    'install.generic.0': 'הופכים את הבוקר לרגוע בלחיצה אחת. הוסיפו את Buff למסך הבית.',
    'install.generic.1': 'בוקר של הצלחות מתחיל כאן. שימו את הכלים שלכם במרכז המסך.',
    'install.generic.2': 'אל תחפשו אותנו בדפדפן בכל בוקר. Buff מחכה לכם על מסך הבית.',
    'install.generic.3': 'גישה מהירה לבוקר שפוי. התקינו את האפליקציה עכשיו.',

    // Old ParentDashboard
    'oldDashboard.familySettings': 'הגדרות משפחה',
    'oldDashboard.familySettingsDesc': 'הגדרות כלליות וקוד משפחה',
    'oldDashboard.appName': 'שם האפליקציה',
    'oldDashboard.defaultGoal': 'יעד יומי ברירת מחדל',
    'oldDashboard.credits': 'קרדיטים',
    'oldDashboard.lessonReminders': 'תזכורות שיעורים',
    'oldDashboard.fridaySchoolDay': 'יום שישי יום לימודים',
    'oldDashboard.uploadSchedule': 'העלאת מערכת',
    'oldDashboard.manageSchedule': 'ניהול מערכת וציוד',

    // Pet Evolution
    'pet.stage.egg': 'ביצה',
    'pet.stage.hatchling': 'גוזל',
    'pet.stage.scout': 'סייר',
    'pet.stage.guardian': 'שומר',
    'pet.evolutionProgress': 'התקדמות אבולוציה',
    'pet.maxEvolution': 'אבולוציה מקסימלית!',
    'pet.daysToEvolve': 'ימים להתפתחות',
    'pet.streak': 'רצף',
    'pet.restCards': 'כרטיסים',
    'pet.evolved': 'התפתחות! 🎉',
    'pet.restCardUsed': 'כרטיס מנוחה נוצל! הרצף שלך מוגן 🛡️',
    'pet.restCardUsedMessage': 'זה בסדר לנוח! השתמשתי בכרטיס מנוחה כדי לשמור על הרצף שלך. בוא נחזור לפעולה מחר כדי לעזור לי לצמוח!',
    'pet.buyRestCard': 'קנה כרטיס מנוחה',
    'pet.buyRestCardDesc': 'הגן על הרצף שלך ביום עמוס',
    'pet.lastRestCardUsedNotif': 'שימו לב: {name} השתמש/ה הרגע בכרטיס המנוחה האחרון שלו. זה זמן מצוין לעודד אותו/ה על ההתמדה עד עכשיו, ואולי להציע כרטיס חדש כפרס על מאמץ מיוחד מחר! 🛡️',
    'pet.noRestCards': 'אין כרטיסי מנוחה',
    'pet.grantRestCard': 'הענק כרטיס מנוחה',
    'pet.restCardGranted': 'כרטיס מנוחה הוענק ל{name}!',
  },
  en: {
    // General
    'app.tagline': 'Buff your routine, unlock your potential',
    'app.syncProgress': 'Sign in to sync your progress across devices',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.displayName': 'Display Name',
    'auth.yourName': 'Your name',
    'auth.iAm': 'I am a...',
    'auth.parent': 'Parent',
    'auth.teen': 'Teen',
    'auth.familyCode': 'Family Code',
    'auth.familyCodePlaceholder': 'Paste the code from your parent',
    'auth.familyCodeHint': 'Ask your parent for the family code to join their family.',
    'auth.loggingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.connect': 'Power Up',
    'auth.createAccount': 'Create Account',
    'auth.fillAllFields': 'Please fill in all fields',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.enterFamilyCode': 'Please enter the family code from your parent',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.emailExists': 'This email is already registered',
    'auth.invalidFamilyCode': 'Invalid family code format',
    'auth.welcomeBack': 'Welcome back!',
    'auth.accountCreated': 'Account created! Welcome to the family!',
    'auth.orContinueWith': 'or continue with',
    'auth.continueWithGoogle': 'Sign in with Google',
    'auth.signupWithGoogle': 'Sign up with Google',
    'auth.googleRoleSelection': 'After signing in, you can choose to register as a parent or child',
    'auth.googleSetupRequired': 'To use Google login, please set up your user details first',
    
    // Navigation
    'nav.features': 'Features',
    'nav.howItWorks': 'How It Works',
    'nav.forParents': 'For Parents',
    'nav.login': 'Log In',
    'nav.getStarted': 'Get Started',
    
    // Landing Page
    'landing.basedOnCogFun': 'Based on Executive Function Principles',
    'landing.executiveFunction': 'The Executive Function',
    'landing.powerUp': 'Power-up',
    'landing.heroDescription': 'Master your daily routine with research-based strategies designed for the ADHD brain.',
    'landing.tryFree': 'Try BUFF for Free',
    'landing.seeHow': 'See How It Works',
    'landing.unlockBuffs': 'Unlock Your Daily Buffs',
    'landing.unlockDescription': 'Cognitive power-ups that transform overwhelming tasks into achievable victories.',
    'landing.activateBuffs': 'Activate Daily Buffs',
    'landing.activateDescription': 'Use cognitive strategies to break through task paralysis and conquer "Mountain" assignments one step at a time.',
    'landing.familySync': 'Family Sync',
    'landing.familySyncDescription': 'Collaborative goal setting where the parent is the coach and the teen is the hero of their own journey.',
    'landing.smartInsights': 'Smart Insights',
    'landing.smartInsightsDescription': 'A data-driven dashboard that helps parents identify patterns and offer the right support at the right time.',
    'landing.powerUpsFor': 'Power-ups for the ADHD Brain',
    'landing.powerUpsDescription': 'BUFF uses a professional, research-backed approach to provide personalized cognitive strategies exactly when your teen needs them most.',
    'landing.environmentBuffs': 'Environment Buffs',
    'landing.environmentDescription': 'Optimize your space for focus and reduce sensory distractions.',
    'landing.focusBuffs': 'Focus Buffs',
    'landing.focusDescription': 'Break down overwhelming tasks into micro-achievements.',
    'landing.energyBuffs': 'Energy Buffs',
    'landing.energyDescription': 'Self-regulation techniques to manage energy and emotions.',
    'landing.forParentsTitle': 'For Parents: Be the Coach, Not the Boss',
    'landing.forParentsDescription': 'BUFF empowers parents with insights and strategies to support their teen\'s executive function development without micromanaging. Collaboration over control.',
    'landing.patternRecognition': 'Pattern Recognition',
    'landing.patternDescription': 'Identify when and where struggles happen to offer targeted support.',
    'landing.coachingTips': 'Coaching Tips',
    'landing.coachingDescription': 'Receive research-based suggestions for supporting your teen.',
    'landing.collaborativeGoals': 'Collaborative Goals',
    'landing.collaborativeDescription': 'Set rewards and milestones together as a team.',
    'landing.readyToPowerUp': 'Ready to Power Up?',
    'landing.joinFamilies': 'Join families who are transforming daily routines into achievable victories.',
    'landing.startFreeTrial': 'Start Your Free Trial',
    'landing.researchBacked': 'Based on Executive Function Principles — Research-backed cognitive strategies',
    
    // Dashboard
    'dashboard.dailyXP': 'Daily XP',
    'dashboard.todaysTasks': "Today's Tasks",
    'dashboard.completed': 'Completed',
    'dashboard.pending': 'Pending',
    'dashboard.buffActivated': 'Buff Activated!',
    'dashboard.noTasks': 'No tasks for today',
    
    // Tasks
    'task.morning': 'Morning',
    'task.afternoon': 'Afternoon',
    'task.evening': 'Evening',
    'task.medication': 'Medication',
    'task.hygiene': 'Hygiene',
    'task.nutrition': 'Nutrition',
    'task.school': 'School',
    
    // Settings
    'settings.title': 'Settings',
    'settings.general': 'General',
    'settings.language': 'Language',
    'settings.hebrew': 'עברית',
    'settings.english': 'English',
    'settings.dailyGoal': 'Daily Goal',
    'settings.appTitle': 'App Title',
    'settings.lessonReminders': 'Lesson Reminders',
    'settings.save': 'Save',
    'settings.cancel': 'Cancel',
    'settings.parentSettings': 'Parent Settings',
    'settings.signOut': 'Sign Out',
    
    // Parent Mode
    'parent.overview': 'Overview',
    'parent.children': 'Children',
    'parent.tasks': 'Tasks',
    'parent.timetable': 'Timetable',
    'parent.rewards': 'Rewards',
    'parent.insights': 'Insights',
    'parent.familyCode': 'Family Code',
    'parent.shareCode': 'Share Code',
    'parent.sendToChild': 'Send to Child',
    'parent.noChildren': 'No children registered yet',
    'parent.inviteChild': 'Invite a child to join the family',
    
    // Rewards Store
    'store.title': 'Rewards Store',
    'store.subtitle': 'Redeem your earned credits',
    'store.balance': 'Balance',
    'store.totalBalance': 'Total Balance',
    'store.claim': 'Redeem',
    'store.claimed': 'Claimed',
    'store.locked': 'Locked',
    'store.notEnough': 'Not enough credits',
    'store.availableRewards': 'Available Rewards',
    'store.claimedRewards': 'Claimed Rewards',
    'store.noRewards': 'No Rewards Yet',
    'store.askParent': 'Ask your parent to add some awesome rewards!',
    'store.vaultEmpty': 'The Vault is Empty',
    'store.askParentToAdd': 'Ask your parent to add rewards to your quest!',
    'store.credits': 'credits',
    'store.rewardPurchased': '🎉 Reward Claimed!',
    'store.enjoy': 'Enjoy!',
    'store.unclaim': 'Unclaim',
    'store.unclaimConfirmTitle': '↩️ Unclaim Reward?',
    'store.unclaimConfirmDesc': 'will return to the store',
    'store.unclaimCreditsReturn': 'credits will be refunded',
    'store.unclaimSuccess': '↩️ Reward Returned',
    'store.unclaimCreditsReturned': 'credits refunded',
    'store.confirmCancel': 'Cancel',
    'store.confirmOk': 'Confirm',
    'store.effortMessage': 'Everything here you earned through your own hard work! 💪',
    
    // Pet
    'pet.resting': '😴 Your pet is resting...',
    'pet.restEncouragement': 'Time to go do something fun in the real world!',
    'pet.happyReaction': 'Woohoo!',
    'pet.restingTitle': 'Rest Time',
    'pet.restMessage': "I'm all charged up! Going to rest while you go conquer the world. See you after your next task!",
    'pet.levelUp': 'Level Up! 🎉',
    'pet.greeting.ready': 'Hey {name}! Ready for your next mission?',
    'pet.greeting.awesome': '{name}, you are awesome! 💪',
    'pet.greeting.mission': "Let's conquer the next mission together!",
    'pet.greeting.believe': 'I believe in you, {name}! 🌟',
    'pet.skin.dragon': 'Dragon',
    'pet.skin.robot': 'Robot',
    'pet.skin.cat': 'Cat',
    'pet.skin.fox': 'Fox',
    'pet.skin.unicorn': 'Unicorn',
    'pet.skin.owl': 'Owl',
    'pet.skin.bear': 'Bear',
    'pet.skin.dino': 'Dinosaur',
    
    // Navigation tabs
    'nav.tasks': 'Tasks',
    'nav.timetable': 'Timetable',
    'nav.progress': 'Progress',
    'nav.store': 'Store',
    'nav.settings': 'Settings',
    
    // Focus Fuel
    'fuel.charging': 'Focus Level: Charging...',
    'fuel.halfway': 'Halfway there! Excellent!',
    'fuel.almostFull': 'Almost there! Keep going!',
    'fuel.full': 'Fully Charged! Time for a break?',
    'fuel.skillBadge': 'Skill Badge',
    'fuel.buffs': 'Buffs',
    'fuel.dailyReset': 'Meter resets every morning - every day is a fresh start!',
    'fuel.offDay': '🌴 Off Day',
    'fuel.schoolDay': '📚 School Day',
    'fuel.goal': 'Goal',
    'fuel.goalOf': 'of',
    
    // Progress (legacy)
    'progress.dailyXP': 'Daily XP',
    'progress.levelComplete': 'Level Complete! 🎉',
    'progress.keepGoing': 'Keep powering up!',
    'progress.level': 'Level',
    'progress.maxLevel': 'Max Level!',
    
    // Focus Mode
    'focus.active': '🎯 Focus Mode Active',
    'focus.completeFirst': 'Complete this task before moving on',
    'focus.allComplete': 'All Tasks Complete!',
    'focus.greatWork': 'Great work! You can move to the next phase.',
    'focus.remaining': 'tasks remaining',
    
    // Common
    'common.loading': 'Loading...',
    'common.loadingDataFor': 'Loading data for',
    'common.child': 'child',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.credits': 'Credits',
    'common.xp': 'XP',
    'common.backToTasks': 'Back to Tasks',
    'tasks': 'Tasks',
    'noTasksForPhase': 'No tasks for this phase',
    
    // Legal
    'legal.title': 'Legal Disclaimer',
    'legal.disclaimer': 'Important Disclaimer: The Buff app is a technological tool for task management and organization, developed based on personal experience and tools from product management and parenting. The use of the app, including the "insights" it provides, is intended for enrichment and assistance purposes only and does not constitute a substitute for medical, psychological, diagnostic, or professional therapeutic advice. The app\'s creator is not a licensed therapist, doctor, or psychologist. For any questions regarding your child\'s physical or mental health, please consult qualified professionals. Use of the app is at the user\'s sole responsibility.',
    'legal.termsLink': 'Terms of Use and Legal Disclaimer',
    'legal.footerLink': 'Legal Disclaimer',
    'legal.consentText': 'By signing in, I agree to the',
    
    // Welcome Banner
    'welcome.title': 'Welcome to BUFF',
    'welcome.message': 'We\'ve set up some starter quests for your daily routine. You can customize them anytime in the settings!',
    'welcome.tasksReady': '✨ 8 quests ready and waiting!',
    'welcome.letsGo': 'Let\'s Go!',

    // Phase Transition Banner
    'phase.schoolEnded': '🎉 School Day is Over!',
    'phase.switchToAfternoon': 'Switching to Afternoon tasks',
    'phase.schoolStarted': '📚 Time for School!',
    'phase.switchToSchool': 'Switching to School Day',
    'phase.transition': 'Phase Transition',

    // New Day Banner
    'newDay.title': 'Good Morning!',
    'newDay.subtitle': 'New Quests are ready. Fresh day, new opportunities! 🚀',

    // Birthday Celebration
    'birthday.title': '🎉 Happy Birthday! 🎉',
    'birthday.forYou': 'you!',
    'birthday.years': 'years!',
    'birthday.wish': 'Wishing you an amazing day full of joy and achievements! ✨',
    'birthday.thanks': 'Thanks! 🥳',

    // Pack Completion Celebration
    'celebration.greatJob': 'Great Job!',
    'celebration.champ': 'Champ',
    'celebration.focusMuscles': 'You used your focus muscles today! 💪',
    'celebration.effortMessage': 'You earned this through your hard work!',
    'celebration.creditsEarned': 'Credits Earned',
    'celebration.continue': 'Keep Going! 🚀',

    // Parent Daily Win Card
    'dailyWin.title': 'Daily Win!',
    'dailyWin.completedTasks': 'completed {count} of {total} tasks',
    'dailyWin.momentum': 'Daily Momentum',
    'dailyWin.coachingTitle': 'Coaching Moment',
    'dailyWin.coachingTip': '{name} just finished their tasks! This is a great time to give them a long hug or a specific compliment about their effort.',
    'dailyWin.viewInsight': 'View Deep Insight',

    // View As Child Banner
    'viewAsChild.viewing': 'Viewing as ',
    'viewAsChild.backToParent': 'Back to Parent',

    // Gear Master
    'gear.nightMission': 'Night Mission - Readiness Bonus!',
    'gear.morningReminder': 'Morning Reminder - Bag Check',
    'gear.bagReady': 'Bag is ready! ✨',
    'gear.prepTomorrow': 'Prepare gear for tomorrow now',
    'gear.checkBag': 'Make sure everything is in the bag before leaving',
    'gear.tomorrowOff': 'Tomorrow is a day off! 🎉',
    'gear.noScheduleTomorrow': 'No schedule for tomorrow 📋',
    'gear.noBagPrep': 'No need to prepare a bag - enjoy the rest!',
    'gear.addSchedule': 'Add a timetable in Parent Settings to enable the Night Mission.',
    'gear.nightCompleted': 'Night Mission - Complete! 🌟',
    'gear.bagReadyCredits': 'Bag is ready for tomorrow - earned',
    'gear.noSpecialEquipment': 'No special equipment needed',
    'gear.bagComplete': 'Bag prep complete!',
    'gear.credits': 'credits',
    'gear.nightMissionComplete': '🎒 Night Mission Complete!',
    'gear.nightMissionCompleteDesc': 'Great work! Preparing the bag early earned',
    'gear.undo': 'Undo (5 seconds)',
    'gear.undone': '↩️ Undone',
    'gear.undoneDesc': 'Night Mission was undone',
    'gear.markAll': 'Check all items',
    'gear.itemsReady': 'items ready',
    'gear.eveningPrep': '🧹 Evening Prep:',
    'gear.equipmentNeeded': '🎒 Equipment needed for lessons:',
    'gear.lunchboxReset': 'Daily Reset: Empty and clean lunch bag (container to dishwasher/trash)',
    'gear.prepNow': 'Prepare gear now!',
    'gear.noPoints': 'No points',
    'gear.morningCheck': 'Check that everything is in the bag before leaving!',
    'gear.morningTip': '💡 Tip: Preparing the bag the night before earns points!',
    'gear.equipmentRequired': 'Equipment Required',

    // Daily Essentials
    'essentials.title': 'Before Leaving the House',
    'essentials.noPoints': 'No points',
    'essentials.allReady': 'All set to go! 🚀',
    'essentials.waterBottle': 'Water Bottle',
    'essentials.food': 'Food/Sandwich',
    'essentials.phone': 'Phone',
    'essentials.keys': 'Keys',

    // My Progress
    'myProgress.title': 'My Progress',
    'myProgress.weeklySummary': 'Weekly Summary',
    'myProgress.weeklyMomentum': 'Weekly Momentum',
    'myProgress.noActiveTasks': 'No active tasks right now',
    'myProgress.rechargeTime': 'Great time to recharge! 🔋✨',
    'myProgress.outOf7': 'of 7 ✓',

    // Weekly Goal Ring
    'weeklyGoal.title': 'Weekly Goal',
    'weeklyGoal.outOf': 'of',
    'weeklyGoal.perfect': '🏆 Perfect!',
    'weeklyGoal.goalReached': '🎯 Goal Reached!',
    'weeklyGoal.almostThere': '💪 Almost There!',
    'weeklyGoal.keepGoing': '🚀 Keep Going!',
    'weeklyGoal.progress': 'Progress',
    'weeklyGoal.goal70': 'Goal 70%',

    // Ticket Wallet
    'tickets.title': 'Ticket Wallet',
    'tickets.available': 'available',
    'tickets.rest': 'Rest',
    'tickets.none': '😴 No rest tickets available',
    'tickets.oneLeft': '🌟 One rest ticket left!',
    'tickets.multiple': '✨ You have rest tickets',
    'tickets.infoTitle': 'How do Rest Tickets work?',
    'tickets.rule1': 'Every',
    'tickets.rule1Tasks': '5 tasks',
    'tickets.rule1End': 'you complete successfully earn you one rest ticket.',
    'tickets.rule2': 'You can use a ticket to',
    'tickets.rule2Skip': '"skip"',
    'tickets.rule2End': 'a day without hurting your weekly goal (the 70%).',
    'tickets.rule3': 'Rest is part of the coaching! 💪',
    'tickets.rule3Tip': 'Use them wisely on busy days.',
    'tickets.gotIt': 'Got it! 🚀',

    // School Day Section
    'school.equipmentRequired': 'Equipment Required',
    
    // DailySchedule
    'schedule.todaysSchedule': "Today's Schedule",
    'schedule.weekend': 'Weekend - No classes',
    'schedule.enjoyWeekend': '🎉 Enjoy your weekend!',
    'schedule.noSubjects': 'No subjects set',
    'schedule.setupTimetable': 'Set up your timetable in Parent Mode to see your daily schedule.',
    'schedule.lessons': 'lessons',
    'schedule.period': 'Period',
    'schedule.now': 'Now',

    // Timetable (WeeklyTimetable)
    'timetable.lessons': 'lessons',
    'timetable.plannedLessons': 'planned lessons',
    'timetable.add': '+ Add',
    'timetable.editAll': 'Edit All',
    'timetable.noLessons': 'No lessons for this day',
    'timetable.addFirst': '+ Add first lesson',
    'timetable.weekOverview': 'Week Overview',
    'timetable.time': 'Time',
    'timetable.subjectPlaceholder': 'Subject name',
    'timetable.equipmentRequired': 'Equipment required',
    'timetable.equipmentPlaceholder': 'Notebook, textbook...',
    'timetable.clickToAdd': 'Click to add subject...',

    // TomorrowsPrep
    'prep.tomorrowOff': 'Tomorrow is a day off! 🎉',
    'prep.noBagPrep': 'No bag prep needed - enjoy the rest!',
    'prep.prepForTomorrow': 'Prep for Tomorrow',
    'prep.noSpecialEquipment': 'No special equipment defined for tomorrow',
    'prep.equipmentChecklist': 'Equipment Checklist',
    'prep.bagReady': 'Bag packed? Awesome! Tomorrow will be easier 💪',

    // Brand Terminology (Buff Positive Coaching DNA)
    'brand.holdingSpace': 'Holding Space',
    'brand.boundaries': 'Boundaries',
    'brand.strategies': 'Strategies',
    'brand.coaching': 'Coaching',
    'brand.readiness': 'Readiness',
    'brand.positiveReinforcement': 'Positive Reinforcement',

    // Parent Settings
    'parentSettings.title': 'Settings',
    'parentSettings.buffSettings': 'Buff Settings',
    'parentSettings.editTasksRewards': 'Edit tasks, timetable & rewards',
    'parentSettings.generalAndChildren': 'General settings & child management',
    'parentSettings.back': 'Back',
    'parentSettings.generalSettings': 'General Settings',
    'parentSettings.familyDefaults': 'Family default settings',
    'parentSettings.appName': 'App Name',
    'parentSettings.lessonReminders': 'Lesson Reminders',
    'parentSettings.updatesFromAdi': 'Updates & tips from Adi',
    'parentSettings.weekendTips': 'Weekend tips & new features',
    'parentSettings.subscribedUpdates': 'Subscribed to updates!',
    'parentSettings.unsubscribedUpdates': 'Unsubscribed from updates',
    'parentSettings.settingsError': 'Error updating settings',
    'parentSettings.childManagement': 'Child Management',
    'parentSettings.noChildrenYet': 'No children have joined yet',
    'parentSettings.learningGuidance': 'Learning & Guidance',
    'parentSettings.understandApproach': 'Understanding the Buff approach',
    'parentSettings.worldView': 'Our Philosophy',
    'parentSettings.about': 'About',
    'parentSettings.signOutAccount': 'Sign Out',
    'parentSettings.personalBuffSettings': 'Personal Buff Settings',
    'parentSettings.balance': 'Balance',
    'parentSettings.dailyGoal': 'Daily Goal',
    'parentSettings.birthDate': 'Birth Date',
    'parentSettings.schoolQuest': 'School Quest',
    'parentSettings.nightMissionBonus': 'Night Mission - Readiness Bonus',
    'parentSettings.buffPoints': 'Buff Points',
    'parentSettings.tasks': 'Tasks',
    'parentSettings.schedule': 'Schedule',
    'parentSettings.rewards': 'Rewards',
    'parentSettings.uploadSchedule': 'Upload Schedule',
    'parentSettings.manageScheduleEquipment': 'Manage Schedule & Equipment',
    'parentSettings.lessonsConfigured': 'lessons configured',
    'parentSettings.editRewardsStore': 'Edit Rewards Store',
    'parentSettings.noRewardsConfigured': 'No rewards configured',
    'parentSettings.clickToAdd': 'Click "Edit Rewards Store" to add some',
    'parentSettings.sold': 'Sold',
    'parentSettings.deleteChild': 'Delete Child',
    'parentSettings.deleteProfileAndData': 'Delete profile and all data',
    'parentSettings.deleteConfirm': 'Delete',
    'parentSettings.deleteWarning': 'This action will delete all tasks, credits and rewards for this child. This cannot be undone.',
    'parentSettings.delete': 'Delete',
    'parentSettings.cancel': 'Cancel',
    'parentSettings.deletedSuccess': 'deleted successfully',
    'parentSettings.deleteError': 'Error deleting child',
    'parentSettings.avatarUpdated': 'Avatar updated!',
    'parentSettings.avatarError': 'Error updating avatar',
    'parentSettings.balanceUpdated': 'Balance updated successfully!',
    'parentSettings.balanceError': 'Error updating balance',
    'parentSettings.invalidBalance': 'Please enter a valid balance (0 to 1,000,000)',
    'parentSettings.goalUpdated': 'Goal updated successfully!',
    'parentSettings.goalError': 'Error updating goal',
    'parentSettings.invalidGoal': 'Please enter a valid goal (10 to 1000)',
    'parentSettings.birthDateSaved': 'Birth date saved!',
    'parentSettings.birthDateError': 'Error saving birth date',
    'parentSettings.bagPrepCreditsUpdated': 'Bag prep credits updated!',
    'parentSettings.bagPrepCreditsError': 'Error updating',
    'parentSettings.invalidBagPrepCredits': 'Please enter a valid amount (5 to 100)',
    'parentSettings.schoolQuestActivated': 'School Quest activated! 🎓',
    'parentSettings.schoolQuestActivatedDesc': 'Now fill in the timetable to help your child get focused at school!',
    'parentSettings.schoolQuestTipTitle': 'School Quests activated! 🎓',
    'parentSettings.schoolQuestTipDesc': 'Fill in timetable for school focus',
    'parentSettings.whyTimetable': '💡 Why a timetable?',
    'parentSettings.timetableExplanation': 'The timetable helps your child track moments of focused learning and identify when concentration is harder. It\'s a tool for self-awareness, not criticism.',
    'parentSettings.schoolQuestDisabledWarning': '⚠️ School Quest is currently off - the timetable won\'t be shown to the child. Enable it in settings above.',
    'parentSettings.fridayAutoEnabled': 'Friday was automatically enabled because the timetable contains Friday lessons',
    'parentSettings.taskUpdated': 'Task updated successfully',
    'parentSettings.addTask': 'Add Task',
    'parentSettings.taskName': 'Task Name',
    'parentSettings.activeDays': 'Active Days',
    'parentSettings.additionalDetails': 'Additional details or equipment (optional)',
    'parentSettings.detailsPlaceholder': 'e.g.: Bring art folder, don\'t forget water bottle...',
    'parentSettings.save': 'Save',
    'parentSettings.noTasksYet': 'No tasks yet',
    'parentSettings.credits': 'credits',
    'parentSettings.copyToChild': 'Copy to another child',
    'parentSettings.taskCopied': 'Task copied',
    'parentSettings.rewardCopied': 'Reward copied',
    'parentSettings.toChildren': 'children',
    'parentSettings.copyError': 'Error copying',
    'parentSettings.noFamilyFound': 'No family found',
    'parentSettings.childAddedSuccess': 'added successfully! 🎉',
    'parentSettings.childCreateError': 'Error creating child profile',

    // Category options
    'category.learning': 'Learning',
    'category.organization': 'Organization',
    'category.selfCare': 'Self-Care',
    'category.responsibility': 'Home & Responsibility',
    'category.movement': 'Body & Movement',

    // Parent Bottom Navigation
    'parentNav.monitoring': 'Monitoring',
    'parentNav.settings': 'Settings',
    'parentNav.reports': 'Reports',
    'parentNav.viewAsChild': 'View as Child',

    // Parent Family Overview
    'overview.familyOverview': 'Family Overview',
    'overview.realTimeTracking': 'Real-time progress tracking',
    'overview.now': 'Now',
    'overview.morning': 'Morning',
    'overview.school': 'School',
    'overview.afternoon': 'Afternoon',
    'overview.evening': 'Evening',
    'overview.myChildren': 'My Children',
    'overview.creditsAccumulated': 'credits accumulated',
    'overview.outOf': 'of',
    'overview.todayProgress': "Today's Progress",
    'overview.tasks': 'Tasks',
    'overview.lessons': 'Lessons',
    'overview.awardingBonus': 'Awarding bonus...',
    'overview.bonusAwarded': 'Great Day bonus awarded ✓',
    'overview.greatDay': '🌟 Especially great day! (+20)',
    'overview.viewAsChild': 'View as Child',

    // Parent View
    'parentView.loading': 'Loading...',
    'parentView.child': 'Child',
    'parentView.addChildTitle': 'Add New Child',

    // Welcome Home Screen
    'welcome.addFirstChild': 'Add your first child',
    'welcome.startJourney': 'To start the shared journey',
    'welcome.connectChildForInsights': 'Connect a child to unlock these insights',
    'welcome.weeklySuccess': 'Weekly success rate',
    'welcome.insightsComingSoon': 'Insights & progress - coming soon',

    // First Task Nudge Card
    'nudge.readyToStart': 'Hey {name}, ready to start?',
    'nudge.profileSetup': 'Profile is set up, now just pick the first task to start earning points.',
    'nudge.addFirstTask': 'Add First Task',

    // Setup Progress Header
    'setup.almostDone': 'Just a little more to complete BUFF setup',
    'setup.missing': 'Missing',
    'setup.addChild': 'Add child',
    'setup.configureTasks': 'Configure tasks',
    'setup.configureRewards': 'Configure rewards',
    'setup.timetable': 'Timetable',

    // Parent Welcome Banner
    'parentWelcome.title': 'Welcome to Buff',
    'parentWelcome.noChildrenMsg': 'Ready to start? We\'ll help you set up your child\'s profile, tasks, and rewards in 2 minutes.',
    'parentWelcome.hasChildrenMsg': 'We\'ve prepared the most professional framework for managing the day. We recommend starting by reading "Our Philosophy" to get the most out of the process.',
    'parentWelcome.letsStart': 'Let\'s Start! 🚀',
    'parentWelcome.readFirst': 'Let me read about the method first',
    'parentWelcome.learnMore': 'Learn more about the method',
    'parentWelcome.skipStart': 'Skip, I\'ll start on my own',

    // Parent Reports
    'reports.title': 'Weekly Buff Stats',
    'reports.analysis': 'Analysis & insights',
    'reports.weeklyAnalysis': 'Weekly analysis & insights',
    'reports.loadingReports': 'Loading reports...',
    'reports.noChildrenYet': 'No children to analyze yet',
    'reports.loadingInsights': 'Loading insights...',
    'reports.selectChild': 'Select child',
    'reports.phasePerformance': 'Performance by Phase',
    'reports.strong': 'Strong',
    'reports.igniting': 'Igniting',
    'reports.bySubject': 'by subject',
    'reports.insightsFor': 'Insights for ',
    'reports.noInsightsYet': 'No insights yet. Check back after a few days of activity.',
    'reports.showLess': 'Show less',
    'reports.more': 'More',
    'reports.difficulty': 'Difficulty',
    'reports.general': 'General',
    'reports.fridaySchoolDay': 'Friday is a School Day',
    'reports.buffPoints': 'Buff Points',
    'reports.streak': 'Streak',
    'reports.quests': 'Quests',
    'reports.lessons': 'Lessons',
    'reports.trendDetector': 'Trend Detector',
    'reports.reflectionLog': 'Reflection Log',

    // Ignition Insights
    'ignition.weeklyAnalysis': 'Weekly Ignition Analysis',
    'ignition.ignitionAnalysis': 'Ignition Analysis',
    'ignition.weeklyRate': 'Weekly Ignition Rate',
    'ignition.goal70': '70% Goal',
    'ignition.aboveGoal': 'above the 70% success threshold!',
    'ignition.onTheWay': 'on the right track - almost at 70%!',
    'ignition.ignitedDays': 'Ignition Days 🔥',
    'ignition.chargingDays': 'Charging Days 🔋',
    'ignition.strongestCategory': 'Strongest Category',
    'ignition.success': 'success',
    'ignition.mostActiveWindow': 'Most Active Time Window',
    'ignition.positiveReinforcement': 'Positive Reinforcement Moment',
    'ignition.weeklyMap': 'Weekly Ignition Map',
    'ignition.ignitedDay': 'Ignition Day',
    'ignition.chargingDay': 'Charging Day',
    'ignition.days': 'days',
    'ignition.actionSuggestion': 'Action Suggestion',
    'phase.morning': 'Morning',
    'phase.school': 'School',
    'phase.afternoon': 'Afternoon',
    'phase.evening': 'Evening',
    'phase.tasks': 'tasks',
    'day.sun': 'Sun',
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',

    // Help Section
    'help.title': 'Help & Installation',
    'help.subtitle': 'Tutorial video and sharing with children',
    'help.videoFallback': 'Your browser does not support video',
    'help.videoLabel': 'Short tutorial - How to install BUFF',
    'help.shareInstallGuide': 'Send installation guide to child:',
    'help.shareMessage': 'Watch this short video to install BUFF on your phone 📱',
    'help.shareSubject': 'Install BUFF',
    'help.email': 'Email',
    'help.copyLink': 'Copy Link',
    'help.copied': 'Copied!',
    'help.linkCopied': 'Link copied!',
    'help.copyError': 'Failed to copy',

    // Join Family
    'joinFamily.title': 'Join Family',
    'joinFamily.subtitle': 'Join an existing family with a family code',
    'joinFamily.codeLabel': 'Family Code (6 characters)',
    'joinFamily.codeError6': 'Family code must be 6 characters',
    'joinFamily.codeErrorAlphanumeric': 'Family code must contain only letters and numbers',
    'joinFamily.joinError': 'Error joining family',
    'joinFamily.invalidCode': 'Invalid code, please verify it matches the code shown on your partner\'s device',
    'joinFamily.success': 'Successfully joined the family!',
    'joinFamily.joining': 'Joining...',
    'joinFamily.join': 'Join Family',
    'joinFamily.hint': 'Ask your partner for the family code from their settings',

    // Duplicate Modal
    'duplicate.copyTask': 'Copy Task',
    'duplicate.copyReward': 'Copy Reward',
    'duplicate.copying': 'Copying:',
    'duplicate.noOtherChildren': 'No other children in the family',
    'duplicate.addChildHint': 'Add another child to use this feature',
    'duplicate.allChildren': 'To all children',
    'duplicate.copy': 'Copy',
    'duplicate.cancel': 'Cancel',

    // Philosophy Page
    'philosophy.title': 'The Buff Philosophy',
    'philosophy.subtitle': 'A professional guide for parents - The philosophy behind the system',
    'philosophy.share': 'Share',
    'philosophy.back': 'Back',
    'philosophy.fromParents': 'From Parents to Parents',
    'philosophy.intro': 'We know how challenging it is to raise a child with attention and focus difficulties. We\'ve prepared a guide explaining the professional approach behind Buff - a system built in collaboration with experts, based on evidence-based Executive Functioning principles.',
    'philosophy.buffInsight': 'Buff Insight',
    'philosophy.letsStart': 'Got it, let\'s start!',
    'philosophy.tip': '💡 Tip: Share this page with partners, teachers, or therapists - so everyone understands the approach and knows how to support your child consistently.',
    'philosophy.readStory': 'Read the story behind Buff',
    'philosophy.branding.title': 'The Name Buff - Empowerment & Skill Upgrade',
    'philosophy.branding.subtitle': 'Not another task list - but a tool for empowerment',
    'philosophy.branding.content': 'In video games, a "Buff" is a temporary bonus that strengthens a character, enabling them to overcome seemingly impossible challenges. That\'s exactly what we want to give your child.\n\nBuff is not another task management app. It\'s an empowerment system that speaks the language kids understand and love. Your children don\'t "check off tasks" - they "complete quests" and earn "Buff Points" into "The Vault".\n\nThis language isn\'t a gimmick - it creates a deep emotional connection and transforms the challenging daily routine into an adventure your child wants to be part of.',
    'philosophy.branding.insight': 'Research in Executive Functioning shows that intrinsic motivation is built when activities feel meaningful and enjoyable to the child. Familiar gaming language minimizes resistance and increases engagement in children with attention difficulties.',
    'philosophy.rewards.title': 'Reward Strategy - The Dopamine Bridge',
    'philosophy.rewards.subtitle': 'Tiered rewards by "Success Days" (1, 2, 4, 5, 10)',
    'philosophy.rewards.content': 'For an ADHD brain, the distant future is abstract and intangible. Large rewards "in a month" aren\'t motivating - they feel like an eternity.\n\nThat\'s why we built a tiered reward system based on "Success Days":\n\n📱 One day (1x Smart Goal) - Extra screen time or dessert choice\n🎉 Two days (2x Smart Goal) - Skip one annoying chore\n🎬 Four days (4x Smart Goal) - Movie night with popcorn\n🍕 Five days (5x Smart Goal) - Pizza or sushi night\n🎢 Ten days (10x Smart Goal) - Fun day out\n\nThis method creates a "Dopamine Bridge" - small, accessible rewards every couple of days build persistence and self-confidence, while larger rewards teach delayed gratification gradually.',
    'philosophy.rewards.insight': 'Research shows children with ADHD respond better to immediate, proximal reinforcement. Small, frequent rewards are more effective than one large distant reward. Combining both types builds immediate motivation and capacity for delayed gratification.',
    'philosophy.positive.title': 'Positive Reinforcement Only - Safe Harbor',
    'philosophy.positive.subtitle': 'Creating a safe environment without punishments or deductions',
    'philosophy.positive.content': 'We know how hard it is to watch your child struggle with frustration. That\'s why we built a system that creates an emotional "safe harbor" - a place where your child can never lose.\n\nIn Buff, your child can only earn points - never lose them. No negative points, no deductions, no punishments. When a task isn\'t completed, it simply didn\'t earn points - that\'s it.\n\nWhy is this so important? Because children with ADHD experience more criticism and corrections than others. They need a space where they can try, fail, and try again - without fear of punishment.\n\nThe focus is always on what was achieved. This reduces resistance and builds self-confidence.',
    'philosophy.positive.insight': 'Research shows children with ADHD respond better to positive reinforcement than punishments. Negative reinforcement creates anxiety and avoidance, while positive reinforcement builds self-confidence and long-term intrinsic motivation.',
    'philosophy.bonus.title': 'Parent Bonus - Recognizing the Invisible Effort',
    'philosophy.bonus.subtitle': 'A tool for identifying hard work that isn\'t always visible',
    'philosophy.bonus.content': 'We know that much of your child\'s effort is "invisible" - it can\'t be seen. Overcoming the urge to get up from the chair, restraining from reacting, staying focused - all of these require enormous effort that isn\'t documented in tasks.\n\nThat\'s why we gave you a unique tool: "Successful Day Bonus" - 20 Buff Points you award your child once a day, at your discretion.\n\nIt\'s not automatic. It\'s a conscious decision to tell your child: "I saw your effort today."\n\nThis bonus creates an opportunity for positive conversation, strengthens your connection, and teaches your child that effort is valued - even when results aren\'t perfect. It\'s also an opportunity to demonstrate flexibility as parents.',
    'philosophy.bonus.insight': 'Positive parent-child interaction is a critical component in developing Executive Functions. The bonus serves as an "emotional bridge" and strengthens the child\'s sense of Agency - the feeling that they can influence their reality.',
    'philosophy.dayTypes.title': 'Day Types - Energy Management & Burnout Prevention',
    'philosophy.dayTypes.subtitle': 'Automatic adjustment between school days and rest days',
    'philosophy.dayTypes.content': 'Children with ADHD consume more mental energy throughout the day. They "run a marathon while others sprint." That\'s why it\'s crucial to adjust expectations to the type of day.\n\nThe system automatically identifies whether it\'s a "school day" (Sunday-Thursday) or a "rest day" (Friday-Saturday and holidays) and adjusts tasks accordingly:\n\n📚 School day - Focus on efficient morning routine, school preparation, and calming evening routine.\n\n🌴 Rest day - Focus on rest and recovery, helping at home at a relaxed pace, and time for creativity.\n\nThis adjustment prevents burnout. It teaches your child that rest is part of the plan, and that expectations change based on context - an important life lesson.',
    'philosophy.dayTypes.insight': 'Children with ADHD need stable structure, but also adapted flexibility. The ability to identify "day type" and adjust expectations reduces cognitive load and prevents the feeling of failure from unrealistic expectations.',
    'philosophy.smartGoal.title': 'The 70% Goal - Winning Streak',
    'philosophy.smartGoal.subtitle': 'Building success upon success',
    'philosophy.smartGoal.content': 'One of the most important lessons from working with children with ADHD is that goals set too high destroy motivation.\n\nInstead of a fixed "100% of tasks" goal, the system automatically calculates a 70% goal of total possible points for a specific day.\n\nWhy 70%?\n• High enough to challenge the child\n• Low enough to be achievable on a normal day\n• Leaves room for "tough days" without feeling like failure\n\nWhen a child reaches 70%, they feel genuine success. When they exceed 70%, they feel like they\'re "winning the game."\n\nThis creates a "Winning Streak" that builds self-confidence instead of perpetuating chronic failure.',
    'philosophy.smartGoal.insight': 'Unrealistic goals are one of the main causes of dropout from behavioral systems. The 70% rule is based on the principle of "success built upon success" - each achievement strengthens motivation to continue and makes the child want to keep trying.',

    // Onboarding Steps
    'onboarding.step1.title': 'Let\'s meet your heroes',
    'onboarding.step1.subtitle': 'Who\'s joining the BUFF team?',
    'onboarding.step1.childName': 'Child\'s Name',
    'onboarding.step1.namePlaceholder': 'e.g., Noah',
    'onboarding.step1.birthDate': 'Birth Date',
    'onboarding.step1.day': 'Day',
    'onboarding.step1.month': 'Month',
    'onboarding.step1.year': 'Year',
    'onboarding.step1.age': 'Age',
    'onboarding.step1.years': 'years',
    'onboarding.step1.nameError': 'Please enter the child\'s name',
    'onboarding.step1.dateError': 'Please select a full birth date',
    'onboarding.step1.ageError': 'Age must be between 5 and 25',
    'onboarding.step1.birthDateHelp': '💡 The birth date helps us tailor tasks and language to your child\'s stage.',
    'onboarding.step1.cta': 'Let\'s Start! 🚀',
    'onboarding.step1.back': 'Back',
    'onboarding.month.0': 'January',
    'onboarding.month.1': 'February',
    'onboarding.month.2': 'March',
    'onboarding.month.3': 'April',
    'onboarding.month.4': 'May',
    'onboarding.month.5': 'June',
    'onboarding.month.6': 'July',
    'onboarding.month.7': 'August',
    'onboarding.month.8': 'September',
    'onboarding.month.9': 'October',
    'onboarding.month.10': 'November',
    'onboarding.month.11': 'December',

    // Step 2
    'onboarding.step2.title': 'Where would you most like to succeed this week?',
    'onboarding.step2.subtitle': 'Choose one area:',
    'onboarding.step2.homework': 'Homework & Practice',
    'onboarding.step2.homeworkDesc': 'Focused learning and academic task success.',
    'onboarding.step2.project': 'Personal Project',
    'onboarding.step2.projectDesc': 'Advance a hobby, coding, or your dream.',
    'onboarding.step2.fitness': 'Fitness & Sports',
    'onboarding.step2.fitnessDesc': 'Consistency in workouts and daily movement.',
    'onboarding.step2.home': 'Home & Organization',
    'onboarding.step2.homeDesc': 'Independence and order in your room and daily life.',

    // Step 3
    'onboarding.step3.title': 'Choose a Starter Pack',
    'onboarding.step3.subtitle': 'Each pack includes pre-set tasks and a custom reward:',
    'onboarding.step3.includes': '📦 Includes {n} pre-set tasks + a custom reward',
    'onboarding.step3.mostPopular': 'Most Popular',
    'onboarding.step3.proPacks': 'Premium Packs',
    'onboarding.step3.proDesc': 'Unlock specialized tracks like "Virtual Pet" or "Social Skills" with BUFF Pro.',
    'onboarding.step3.note': '💡 You can always change this in settings.',
    'onboarding.step3.cta': 'Continue',
    'onboarding.step3.upgradeToUnlock': '🔓 Upgrade to Pro to unlock',
    // Learning packs
    'onboarding.step3.pack.school_quest': 'Attention & Participation',
    'onboarding.step3.pack.school_quest.desc': 'Class prep, active listening & recording homework. Repeats per lesson.',
    'onboarding.step3.pack.homework_hero': 'Homework',
    'onboarding.step3.pack.homework_hero.desc': 'Check for HW, complete it & bonus academic task.',
    // Home packs
    'onboarding.step3.pack.morning_pro': 'Morning Flow',
    'onboarding.step3.pack.morning_pro.desc': 'Ready on time, teeth, healthy breakfast & medication.',
    'onboarding.step3.pack.evening_routine': 'Evening Routine',
    'onboarding.step3.pack.evening_routine.desc': 'Screens off, shower & teeth, bed on time.',
    // Fitness packs
    'onboarding.step3.pack.daily_dash': 'Movement',
    'onboarding.step3.pack.daily_dash.desc': 'Short walk, short sport & long sport.',
    'onboarding.step3.pack.fuel_up': 'Fuel',
    'onboarding.step3.pack.fuel_up.desc': 'Hydration, healthy snack & screen-free play.',
    // Project packs
    'onboarding.step3.pack.steam_startup': 'STEAM / Family Startup',
    'onboarding.step3.pack.steam_startup.desc': 'Creative projects, science & tech — coming soon!',
    // Pack task titles
    'pack.task.class_prep': 'Class Prep',
    'pack.task.active_listening': 'Active Listening',
    'pack.task.record_hw': 'Record Homework',
    'pack.task.check_hw': 'Check for Homework',
    'pack.task.complete_hw': 'Complete Homework',
    'pack.task.bonus_academic': 'Bonus Academic Task',
    'pack.task.ready_on_time': 'Ready on Time',
    'pack.task.teeth_morning': 'Brush Teeth',
    'pack.task.healthy_breakfast': 'Healthy Breakfast',
    'pack.task.medication': 'Medication',
    'pack.task.screens_off': 'Screens Off',
    'pack.task.shower_teeth': 'Shower & Teeth',
    'pack.task.bed_on_time': 'Bed on Time',
    'pack.task.short_walk': 'Short Walk',
    'pack.task.short_sport': 'Short Sport',
    'pack.task.long_sport': 'Long Sport',
    'pack.task.hydration': 'Hydration',
    'pack.task.healthy_snack': 'Healthy Snack',
    'pack.task.screen_free_play': 'Screen-free Play',

    // Step 4
    'onboarding.step4.title': 'Beat the "startup" challenge 🏁',
    'onboarding.step4.tip1': '<strong>Hard to dive into a task?</strong> Set just 15 minutes.',
    'onboarding.step4.tip2': 'Pick something <strong>tiny</strong> that you can finish quickly.',
    'onboarding.step4.tip3': 'Once you start – <strong>dopamine will do the rest!</strong>',
    'onboarding.step4.label': 'My first task:',
    'onboarding.step4.placeholder': 'e.g., Solve one exercise',
    'onboarding.step4.defaultTask': 'Solve one exercise',
    'onboarding.step4.hint': 'This will be the first task on the dashboard 🎯',
    'onboarding.step4.cta': 'Continue',

    // Step 5
    'onboarding.step5.title': 'Turn effort into fun 🎮',
    'onboarding.step5.tip1': '<strong>Every step counts:</strong> Each ✓ on a task earns points.',
    'onboarding.step5.tip2': '<strong>The goal:</strong> Turn daily effort into instant satisfaction.',
    'onboarding.step5.rewardIdeas': 'Reward ideas:',
    'onboarding.step5.label': 'Our weekend reward:',
    'onboarding.step5.placeholder': 'e.g., Family outing or screen time',
    'onboarding.step5.defaultReward': 'Family outing',
    'onboarding.step5.cta': 'Continue',
    'onboarding.step5.reward1': '🎬 Movie night',
    'onboarding.step5.reward2': '🍕 Pizza',
    'onboarding.step5.reward3': '📱 Screen time',
    'onboarding.step5.reward4': '🎮 New game',

    // Step 6
    'onboarding.step6.title': 'Ready for launch! 🚀',
    'onboarding.step6.familyCode': 'Your family code:',
    'onboarding.step6.copied': 'Copied to clipboard! ✓',
    'onboarding.step6.copiedToast': 'Copied! 📋',
    'onboarding.step6.copyError': 'Failed to copy',
    'onboarding.step6.shareWhatsApp': 'Send to {name} via WhatsApp',
    'onboarding.step6.instructionsCopied': 'Instructions copied! 📋 Now paste into WhatsApp or anywhere else',
    'onboarding.step6.instructionsCopiedShort': 'Instructions copied! ✓',
    'onboarding.step6.copyInstructions': 'Copy connection instructions (if WhatsApp didn\'t open)',
    'onboarding.step6.callToAction': 'Time to call <strong>{name}</strong>, download BUFF on their device and enter the family code. The first quest is already waiting inside!',
    'onboarding.step6.launchCta': 'We\'re connected! Let\'s go ⚡',
    'onboarding.step6.creating': 'Creating family...',
    'onboarding.step6.whatsappMessage': '🎮 Hey {name}! Everything is set up in BUFF!\n\n📱 How to join:\n1. Go to the app: {url}\n2. Click "Sign Up"\n3. Choose "I\'m a teen"\n4. Enter the family code:\n\n🔑 {code}\n\nWe\'re waiting for you in the app! 🚀',

    // Clean Day Bonus
    'bonus.alreadyAwarded': 'Successful day bonus already awarded to {name} today!',
    'bonus.awarded': '🌟 {name} received a successful day bonus! +{credits} credits',
    'bonus.error': 'Error awarding bonus',

    // Notifications
    'notification.lessonSoon': '🎯 {subject} lesson starts in 5 minutes!',
    'notification.getReady': 'Time to get ready! 🏆',
    'notification.gearMasterTitle': '🎒 Evening Mission - Readiness Bonus!',
    'notification.gearMasterBody': 'Is the bag ready for tomorrow? Time to earn {credits} Buff Points! ✨',

    // Install Prompt Messages
    'install.personalized.0': 'Turn {names}\'s morning into a success story. Add Buff to your home screen.',
    'install.personalized.1': 'Because {names} deserves to start the day with a smile. Put Buff front and center.',
    'install.personalized.2': 'Ready for a calm morning with {names}? Install the app for quick access.',
    'install.personalized.3': '{names}\'s bridge to independence starts here. Add us to your home screen.',
    'install.generic.0': 'Turn mornings into smooth sailing with one tap. Add Buff to your home screen.',
    'install.generic.1': 'A morning of success starts here. Put your tools front and center.',
    'install.generic.2': 'Don\'t search for us in the browser every morning. Buff is waiting on your home screen.',
    'install.generic.3': 'Quick access to a sane morning. Install the app now.',

    // Old ParentDashboard
    'oldDashboard.familySettings': 'Family Settings',
    'oldDashboard.familySettingsDesc': 'General settings and family code',
    'oldDashboard.appName': 'App Name',
    'oldDashboard.defaultGoal': 'Default Daily Goal',
    'oldDashboard.credits': 'credits',
    'oldDashboard.lessonReminders': 'Lesson Reminders',
    'oldDashboard.fridaySchoolDay': 'Friday is a School Day',
    'oldDashboard.uploadSchedule': 'Upload Schedule',
    'oldDashboard.manageSchedule': 'Manage Schedule & Equipment',

    // Pet Evolution
    'pet.stage.egg': 'Egg',
    'pet.stage.hatchling': 'Hatchling',
    'pet.stage.scout': 'Scout',
    'pet.stage.guardian': 'Guardian',
    'pet.evolutionProgress': 'Evolution Progress',
    'pet.maxEvolution': 'Max Evolution!',
    'pet.daysToEvolve': 'days to evolve',
    'pet.streak': 'streak',
    'pet.restCards': 'cards',
    'pet.evolved': 'Evolved! 🎉',
    'pet.restCardUsed': 'Rest Card used! Your streak is safe 🛡️',
    'pet.restCardUsedMessage': "It's okay to take a break! I used a Rest Card to save your streak. Let's get back to work tomorrow to help me grow!",
    'pet.buyRestCard': 'Buy Rest Card',
    'pet.buyRestCardDesc': 'Protect your streak on a busy day',
    'pet.lastRestCardUsedNotif': "Heads up: {name} just used their last Rest Card. They're out of safety nets! This is a great moment to acknowledge their streak and perhaps offer a new card as a reward for tomorrow's effort! 🛡️",
    'pet.noRestCards': 'No Rest Cards',
    'pet.grantRestCard': 'Grant Rest Card',
    'pet.restCardGranted': 'Rest Card granted to {name}!',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('buff-language');
    return (saved as Language) || 'he';
  });

  useEffect(() => {
    localStorage.setItem('buff-language', language);
    // Set document direction
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
